import { buildClassNames } from "../../../build-classes.js";

/**
 * Every class the marketplace emits, by the role it plays. The names on the
 * page are content hashes of the role and the build, and the build string
 * includes the lab seed, so a class that meant "price" under one seed is a
 * different, meaningless hash under the next. Nothing on the page can be
 * found by what its class says it is.
 *
 * The chat widget is the exception, as it is on a real site: it is a third
 * party's embed with its own stable `hal-` names, which no build of the
 * marketplace touches.
 */
const CLASS_ROLES = [
  "shell", "topBar", "topLinks", "topLink", "headerMain", "logo", "searchForm", "searchInput", "searchSelect", "searchButton", "advanced",
  "menuWrap", "menuButton", "flyout", "flyoutHead", "flyoutList", "flyoutEmpty", "badge", "main", "crumbs", "footer", "footNote",
  "button", "buttonPrimary", "buttonGhost", "divButton", "link", "srOnly", "toastRegion", "toast",
  "consent", "consentText", "consentActions", "consentChoices",
  "scrim", "modal", "modalHead", "modalBody", "modalFoot", "modalClose", "notNow",
  "home", "hero", "heroMedia", "heroInfo", "heroPrice", "heroActions", "tiles", "tile", "strip", "stripCard",
  "results", "rail", "railSection", "railHead", "railList", "railLink", "railCount", "railPrice", "railInput", "railGo",
  "content", "resultsHead", "resultsCount", "tabs", "tab", "tabActive", "tools", "sortWrap", "sortButton", "sortMenu", "sortItem",
  "list", "grid", "card", "cardMedia", "cardImage", "heart", "cardInfo", "cardTitle", "cardBadge", "cardSubtitle", "cardLine",
  "cardPrice", "cardMuted", "cardStrong", "skeleton", "adLabel", "adGhost", "gridCard", "gridBody",
  "pagination", "pageLink", "pageCurrent", "pageArrow", "perPage", "related",
  "item", "gallery", "galleryMain", "galleryThumbs", "galleryHeart", "summary", "itemTitle", "itemSubtitle", "priceBox", "priceBig",
  "priceMeta", "ctaColumn", "sellerCard", "specs", "specRow", "descFrame", "similar", "variantPicker", "variantOption", "itemNumber",
  "drawer", "drawerHead", "drawerBody", "drawerFoot", "chips", "chip", "field", "fieldLabel", "fieldInput", "hint", "trap", "legal", "status",
  "watchlist", "watchRow", "watchInfo", "watchTitle", "watchPrice", "watchMeta",
  "challenge", "challengeCard", "spinner", "promo", "survey", "watchCta", "followCta", "buyDrawer", "bidDrawer", "thumb",
] as const;

export type AuctionClassRole = (typeof CLASS_ROLES)[number];
export type AuctionClasses = Record<AuctionClassRole, string>;

/** The class names of the build the lab seed selects. */
export function auctionClasses(seed: number): AuctionClasses {
  return buildClassNames(`hammerline-web-${seed}`, CLASS_ROLES);
}

/**
 * The emitted stylesheet. The first rules undo the lab's shared page shell,
 * which is centred and narrow; a marketplace is neither. The rest places the
 * things that get in a person's way: a consent banner fixed across the bottom
 * of the window, a chat widget fixed to its bottom-right corner above
 * everything but modals, and a bid drawer whose Confirm button sits exactly
 * where the chat widget's greeting opens.
 */
export function auctionStylesheet(css: AuctionClasses): string {
  const c = (role: AuctionClassRole) => `.${css[role]}`;
  return [
    `body { margin: 0; max-width: none; padding: 0; font: 14px/1.4 "Market Sans", Arial, sans-serif; color: #191919; background: #fff; }`,
    `li { display: list-item; gap: 0; margin: 0; }`,
    `nav { display: block; gap: 0; }`,
    `label { display: inline; margin: 0; }`,
    `button, input, select { font: inherit; }`,
    `[hidden] { display: none !important; }`,
    `${c("srOnly")} { position: absolute; width: 1px; height: 1px; overflow: hidden; clip: rect(0 0 0 0); white-space: nowrap; }`,
    `${c("shell")} { min-height: 100vh; }`,
    `${c("topBar")} { display: flex; justify-content: space-between; padding: 6px 24px; font-size: 12px; border-bottom: 1px solid #e5e5e5; }`,
    `${c("topLinks")} { display: flex; gap: 16px; align-items: center; }`,
    `${c("topLink")} { color: #191919; text-decoration: none; }`,
    `${c("menuWrap")} { position: relative; }`,
    `${c("menuButton")} { border: 0; background: none; padding: 0; cursor: pointer; font-size: 12px; }`,
    `${c("flyout")} { position: absolute; right: 0; top: 20px; z-index: 950; width: 360px; padding: 12px; border: 1px solid #ccc; border-radius: 8px; background: #fff; box-shadow: 0 8px 24px rgba(0,0,0,.18); }`,
    `${c("flyoutHead")} { margin: 0 0 8px; font-weight: 700; }`,
    `${c("flyoutList")} { list-style: none; margin: 0 0 8px; padding: 0; }`,
    `${c("flyoutList")} li { padding: 4px 0; border-bottom: 1px solid #f2f2f2; }`,
    `${c("flyoutEmpty")} { color: #707070; margin: 0 0 8px; }`,
    `${c("badge")} { display: inline-block; min-width: 16px; padding: 0 4px; margin-left: 4px; border-radius: 8px; background: #e0103a; color: #fff; font-size: 11px; text-align: center; }`,
    `${c("headerMain")} { display: flex; align-items: center; gap: 16px; padding: 12px 24px; }`,
    `${c("logo")} { font: 700 30px/1 Georgia, serif; letter-spacing: -1px; color: #3665f3; text-decoration: none; }`,
    `${c("searchForm")} { display: flex; flex: 1; border: 2px solid #191919; border-radius: 24px; overflow: hidden; }`,
    `${c("searchInput")} { flex: 1; border: 0; padding: 10px 16px; }`,
    `${c("searchSelect")} { border: 0; border-left: 1px solid #ccc; padding: 0 8px; }`,
    `${c("searchButton")} { border: 0; padding: 0 28px; background: #3665f3; color: #fff; font-weight: 700; cursor: pointer; }`,
    `${c("advanced")} { font-size: 12px; color: #191919; }`,
    `${c("main")} { padding: 0 24px 200px; }`,
    `${c("crumbs")} { font-size: 12px; color: #707070; margin: 8px 0; }`,
    `${c("footer")} { padding: 24px; border-top: 1px solid #e5e5e5; font-size: 12px; color: #707070; }`,
    `${c("footNote")} { margin: 4px 0; }`,
    `${c("button")} { padding: 8px 18px; border: 1px solid #3665f3; border-radius: 20px; background: #fff; color: #3665f3; cursor: pointer; font-weight: 700; }`,
    `${c("buttonPrimary")} { background: #3665f3; color: #fff; }`,
    `${c("buttonGhost")} { border-color: #ccc; color: #191919; }`,
    `${c("divButton")} { display: inline-block; padding: 8px 18px; border-radius: 20px; background: #3665f3; color: #fff; cursor: pointer; font-weight: 700; user-select: none; }`,
    `${c("link")} { color: #191919; text-decoration: underline; cursor: pointer; }`,
    `${c("toastRegion")} { position: fixed; left: 50%; bottom: 24px; z-index: 1200; transform: translateX(-50%); display: grid; gap: 8px; }`,
    `${c("toast")} { padding: 10px 16px; border-radius: 8px; background: #191919; color: #fff; }`,
    `${c("consent")} { position: fixed; left: 0; right: 0; bottom: 0; z-index: 900; padding: 18px 24px; background: #fff; border-top: 1px solid #ccc; box-shadow: 0 -6px 20px rgba(0,0,0,.15); }`,
    `${c("consentText")} { max-width: 860px; margin: 0 0 12px; }`,
    `${c("consentActions")} { display: flex; gap: 12px; align-items: center; }`,
    `${c("consentChoices")} { margin: 0 0 12px; }`,
    `${c("scrim")} { position: fixed; inset: 0; z-index: 1100; display: grid; place-items: center; background: rgba(0,0,0,.55); }`,
    `${c("modal")} { position: relative; width: min(440px, 92vw); padding: 24px; border-radius: 16px; background: #fff; }`,
    `${c("modalHead")} { margin: 0 0 8px; font-size: 20px; font-weight: 700; }`,
    `${c("modalBody")} { margin: 0 0 16px; }`,
    `${c("modalFoot")} { display: flex; gap: 16px; align-items: center; }`,
    `${c("modalClose")} { position: absolute; top: 12px; right: 12px; width: 24px; height: 24px; cursor: pointer; }`,
    `${c("notNow")} { color: #707070; text-decoration: underline; cursor: pointer; }`,
    `${c("hero")} { display: flex; gap: 24px; padding: 20px; margin: 16px 0; border-radius: 16px; background: #f7f7f7; }`,
    `${c("heroMedia")} { width: 200px; }`,
    `${c("heroInfo")} { flex: 1; }`,
    `${c("heroPrice")} { font-size: 24px; font-weight: 700; margin: 8px 0; }`,
    `${c("heroActions")} { display: flex; gap: 12px; }`,
    `${c("tiles")} { display: flex; flex-wrap: wrap; gap: 12px; margin: 16px 0; }`,
    `${c("tile")} { padding: 12px 16px; border-radius: 24px; background: #f2f2f2; color: #191919; text-decoration: none; }`,
    `${c("strip")} { display: flex; gap: 16px; overflow-x: auto; padding: 8px 0 16px; }`,
    `${c("stripCard")} { flex: 0 0 180px; color: #191919; text-decoration: none; }`,
    `${c("results")} { display: grid; grid-template-columns: 240px minmax(0, 1fr); gap: 24px; }`,
    `${c("rail")} { font-size: 13px; }`,
    `${c("railSection")} { padding: 8px 0 12px; border-bottom: 1px solid #e5e5e5; }`,
    `${c("railHead")} { margin: 0 0 6px; font-weight: 700; cursor: pointer; }`,
    `${c("railList")} { list-style: none; margin: 0; padding: 0; }`,
    `${c("railLink")} { display: block; padding: 3px 0; color: #191919; text-decoration: none; }`,
    `${c("railLink")}[aria-checked="true"]::before { content: "\\2611  "; }`,
    `${c("railLink")}[aria-checked="false"]::before { content: "\\2610  "; }`,
    `${c("railCount")} { color: #707070; }`,
    `${c("railPrice")} { display: flex; gap: 6px; align-items: center; }`,
    `${c("railInput")} { width: 64px; padding: 4px 6px; }`,
    `${c("railGo")} { width: 28px; height: 28px; border-radius: 50%; background: #e5e5e5; display: inline-grid; place-items: center; cursor: pointer; }`,
    `${c("resultsHead")} { display: flex; align-items: center; gap: 16px; padding: 8px 0; }`,
    `${c("resultsCount")} { font-weight: 700; margin: 0; }`,
    `${c("tabs")} { display: flex; gap: 20px; border-bottom: 1px solid #e5e5e5; margin: 0 0 8px; }`,
    `${c("tab")} { padding: 8px 0; color: #191919; text-decoration: none; }`,
    `${c("tabActive")} { border-bottom: 2px solid #191919; font-weight: 700; }`,
    `${c("tools")} { display: flex; justify-content: flex-end; gap: 16px; margin: 0 0 8px; }`,
    `${c("sortWrap")} { position: relative; }`,
    `${c("sortButton")} { border: 1px solid #ccc; border-radius: 16px; background: #fff; padding: 6px 14px; cursor: pointer; }`,
    `${c("sortMenu")} { position: absolute; right: 0; top: 34px; z-index: 700; min-width: 240px; padding: 6px 0; border: 1px solid #ccc; border-radius: 8px; background: #fff; box-shadow: 0 8px 20px rgba(0,0,0,.15); }`,
    `${c("sortItem")} { display: block; padding: 8px 16px; color: #191919; text-decoration: none; }`,
    `${c("list")} { list-style: none; margin: 0; padding: 0; }`,
    `${c("grid")} { list-style: none; margin: 0; padding: 0; display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 16px; }`,
    `${c("card")} { display: flex; gap: 16px; padding: 16px 0; border-bottom: 1px solid #e5e5e5; }`,
    `${c("cardMedia")} { position: relative; flex: 0 0 180px; }`,
    `${c("cardImage")} { width: 180px; height: 180px; border-radius: 12px; background: #f2f2f2; object-fit: cover; }`,
    `${c("heart")} { position: absolute; top: 8px; right: 8px; }`,
    `${c("cardInfo")} { flex: 1; min-width: 0; }`,
    `${c("cardTitle")} { color: #191919; text-decoration: none; font-size: 16px; }`,
    `${c("cardBadge")} { margin-right: 6px; color: #e0103a; font-size: 12px; font-weight: 700; text-transform: uppercase; }`,
    `${c("cardSubtitle")} { color: #707070; margin: 2px 0; min-height: 1em; }`,
    `${c("cardLine")} { margin: 2px 0; min-height: 1em; }`,
    `${c("cardPrice")} { font-size: 20px; font-weight: 700; margin-right: 8px; }`,
    `${c("cardMuted")} { color: #707070; margin-right: 6px; }`,
    `${c("cardStrong")} { font-weight: 700; margin-right: 6px; }`,
    `${c("skeleton")} { display: inline-block; min-width: 72px; height: 1em; border-radius: 4px; background: #eee; }`,
    `${c("adLabel")} { color: #707070; font-size: 12px; }`,
    `${c("adGhost")} { display: none; }`,
    `${c("gridCard")} { display: flex; flex-direction: column; gap: 8px; }`,
    `${c("gridBody")} { display: flex; flex-direction: column-reverse; gap: 2px; }`,
    `${c("pagination")} { display: flex; justify-content: center; align-items: center; gap: 8px; margin: 24px 0; }`,
    `${c("pageLink")} { padding: 6px 12px; border-radius: 16px; color: #191919; text-decoration: none; }`,
    `${c("pageCurrent")} { background: #191919; color: #fff; }`,
    `${c("pageArrow")} { padding: 6px 12px; border: 1px solid #ccc; border-radius: 50%; color: #191919; text-decoration: none; }`,
    `${c("perPage")} { margin-left: 24px; }`,
    `${c("related")} { margin: 16px 0; }`,
    `${c("item")} { display: grid; grid-template-columns: minmax(0, 1fr) 420px; gap: 32px; margin: 16px 0; }`,
    `${c("gallery")} { position: relative; }`,
    `${c("galleryMain")} { width: 100%; max-width: 560px; aspect-ratio: 1; border-radius: 16px; background: #f2f2f2; }`,
    `${c("galleryThumbs")} { display: flex; gap: 8px; margin-top: 8px; }`,
    `${c("galleryHeart")} { position: absolute; top: 12px; left: 12px; width: 40px; height: 40px; border: 0; border-radius: 50%; background: #fff; cursor: pointer; }`,
    `${c("itemTitle")} { font-size: 24px; margin: 0 0 4px; }`,
    `${c("itemSubtitle")} { color: #707070; margin: 0 0 12px; }`,
    `${c("priceBox")} { padding: 12px 0; border-top: 1px solid #e5e5e5; border-bottom: 1px solid #e5e5e5; }`,
    `${c("priceBig")} { font-size: 28px; font-weight: 700; }`,
    `${c("priceMeta")} { color: #707070; margin: 4px 0; }`,
    `${c("ctaColumn")} { display: grid; gap: 10px; margin: 16px 0; }`,
    `${c("sellerCard")} { padding: 12px; margin: 16px 0; border: 1px solid #e5e5e5; border-radius: 12px; }`,
    `${c("specs")} { width: 100%; border-collapse: collapse; margin: 16px 0; }`,
    `${c("specRow")} td { padding: 6px 8px; border-bottom: 1px solid #f2f2f2; }`,
    `${c("descFrame")} { width: 100%; height: 260px; border: 1px solid #e5e5e5; border-radius: 8px; }`,
    `${c("similar")} { min-height: 120px; margin: 24px 0; }`,
    `${c("variantPicker")} { position: relative; border: 1px solid #ccc; border-radius: 8px; padding: 8px 12px; cursor: pointer; }`,
    `${c("variantOption")} { padding: 6px 12px; cursor: pointer; }`,
    `${c("itemNumber")} { color: #707070; font-size: 12px; }`,
    `${c("drawer")} { position: fixed; top: 0; right: 0; bottom: 0; z-index: 800; width: 420px; display: flex; flex-direction: column; background: #fff; box-shadow: -8px 0 24px rgba(0,0,0,.2); }`,
    `${c("drawerHead")} { display: flex; justify-content: space-between; align-items: center; padding: 16px; border-bottom: 1px solid #e5e5e5; font-weight: 700; }`,
    `${c("drawerBody")} { flex: 1; overflow: auto; padding: 16px; }`,
    `${c("drawerFoot")} { padding: 16px; border-top: 1px solid #e5e5e5; }`,
    `${c("drawerFoot")} > * { display: block; width: 100%; box-sizing: border-box; text-align: center; }`,
    `${c("chips")} { display: flex; gap: 8px; margin: 12px 0; }`,
    `${c("chip")} { padding: 6px 12px; border: 1px solid #3665f3; border-radius: 16px; background: #fff; color: #3665f3; cursor: pointer; }`,
    `${c("field")} { display: block; margin: 12px 0; }`,
    `${c("fieldLabel")} { display: block; font-weight: 700; margin-bottom: 4px; }`,
    `${c("fieldInput")} { width: 100%; box-sizing: border-box; padding: 10px; border: 1px solid #ccc; border-radius: 8px; }`,
    `${c("hint")} { color: #707070; font-size: 12px; }`,
    `${c("trap")} { position: absolute; left: -10000px; top: auto; width: 1px; height: 1px; overflow: hidden; }`,
    `${c("legal")} { color: #707070; font-size: 12px; }`,
    `${c("status")} { margin: 12px 0; font-weight: 700; }`,
    `${c("watchlist")} { list-style: none; margin: 0; padding: 0; }`,
    `${c("watchRow")} { display: flex; gap: 16px; padding: 12px 0; border-bottom: 1px solid #e5e5e5; }`,
    `${c("watchInfo")} { flex: 1; }`,
    `${c("watchTitle")} { color: #191919; }`,
    `${c("watchPrice")} { font-weight: 700; }`,
    `${c("watchMeta")} { color: #707070; }`,
    `${c("challenge")} { display: grid; place-items: center; min-height: 80vh; }`,
    `${c("challengeCard")} { max-width: 480px; padding: 32px; border: 1px solid #e5e5e5; border-radius: 16px; text-align: center; }`,
    `${c("spinner")} { width: 32px; height: 32px; margin: 16px auto; border: 4px solid #e5e5e5; border-top-color: #3665f3; border-radius: 50%; animation: hl-spin 1s linear infinite; }`,
    `@keyframes hl-spin { to { transform: rotate(360deg); } }`,
    `#hal-assist { position: fixed; right: 20px; bottom: 20px; z-index: 1000; }`,
    `#hal-assist .hal-launcher { width: 56px; height: 56px; border: 0; border-radius: 50%; background: #0b6e4f; color: #fff; font-weight: 700; cursor: pointer; }`,
    `#hal-greeting { position: fixed; right: 84px; bottom: 20px; z-index: 1000; width: 300px; min-height: 96px; padding: 14px 16px; border-radius: 14px; background: #fff; box-shadow: 0 10px 30px rgba(0,0,0,.25); box-sizing: border-box; cursor: pointer; }`,
    `#hal-greeting .hal-close { position: absolute; top: 6px; right: 8px; width: 20px; height: 20px; line-height: 20px; text-align: center; color: #707070; cursor: pointer; }`,
    `#hal-panel { position: fixed; right: 20px; bottom: 88px; z-index: 1000; width: 340px; height: 420px; border-radius: 14px; background: #fff; box-shadow: 0 10px 30px rgba(0,0,0,.25); padding: 16px; box-sizing: border-box; }`,
  ].join("\n");
}
