/** One row of `lab-runs/index.md`, already decided: `verdict` reads `unfinished` for a run whose process died while it was `running`. */
export type RunsIndexRow = {
  /** `YYYY-MM-DD/<runId>/`, relative to the index. */
  folder: string;
  started: string;
  startedAt: string;
  lane: string;
  task: string;
  verdict: string;
  costUsd: number | null;
  steps: number;
};

/** The index as Markdown, newest run first. */
export function renderRunsIndex(rows: readonly RunsIndexRow[]): string {
  const ordered = [...rows].sort((left, right) => Date.parse(right.startedAt) - Date.parse(left.startedAt) || right.folder.localeCompare(left.folder));
  const lines = [
    "# Lab runs",
    "",
    "Every live Lab run on this machine, newest first. Regenerated by the Lab as each run starts and ends; do not edit.",
    "A run still `running` whose process has gone reads `unfinished`. Each folder's `steps/` holds every model and tool step of the run.",
    "",
    "| Started | Lane | Task | Verdict | Cost | Steps | Folder |",
    "| --- | --- | --- | --- | --- | --- | --- |",
    ...ordered.map(row => `| ${cell(row.started)} | ${cell(row.lane)} | ${cell(row.task)} | ${cell(row.verdict)} | ${row.costUsd === null ? "-" : `$${row.costUsd.toFixed(4)}`} | ${row.steps} | [${cell(row.folder)}](${encodeURI(row.folder)}) |`),
    "",
  ];
  return lines.join("\n");
}

function cell(text: string): string {
  return text.replace(/\|/gu, "\\|").replace(/[\r\n]+/gu, " ");
}
