import type { Listing } from "../types.js";

const DESC_ACCESSORY = ["Genuine part, removed from a working camera.", "Posted in a padded envelope."];

/**
 * Everything around the camera: caps, cases, hoods, straps, a manual, an empty
 * box, film and a flashgun. Most of them name the Kestrel 35 in their title,
 * so a search for it returns them, and two carry the camera's model in their
 * item specifics because their sellers filled the field in with the camera the
 * part fits. The half case is sold in three variations at three prices.
 *
 * The `n` listings do not match a search for "kestrel 35" at all. They fill the
 * home page, stand in the results as advertisements, and one of them is
 * already on the person's watchlist.
 */
export const ACCESSORIES: Readonly<Record<string, Listing>> = {
  a1: { id: "186912210974", title: "Original lens cap for Kestrel 35", subtitle: "", brand: "Kestrel", model: "Not specified", type: "Lens cap", format: "auction", condition: "Pre-owned", currency: "GBP", price: 950, bids: 6, postage: { kind: "paid", amount: 150 }, endsIn: 150, listedAgo: 5600, seller: "oldgrain", watchers: 5, description: DESC_ACCESSORY },
  a2: { id: "226149930885", title: "Leather half case for Kestrel 35 — tan, black or oxblood", subtitle: "Choose your colour", brand: "Unbranded", model: "Not specified", type: "Case", format: "fixed", condition: "Pre-owned", currency: "GBP", price: 1800, priceTo: 2600, bids: 0, postage: { kind: "paid", amount: 250 }, listedAgo: 30000, seller: "rust_and_brass", watchers: 58, variations: [{ label: "Tan", price: 1800 }, { label: "Black", price: 2200 }, { label: "Oxblood", price: 2600 }], description: ["Hand-stitched half case, made to order in three colours."] },
  a3: { id: "204432287716", title: "Kestrel 35 instruction manual (reprint)", subtitle: "", brand: "Kestrel", model: "Not specified", type: "Manual", format: "auction", condition: "Pre-owned", currency: "GBP", price: 420, bids: 2, postage: { kind: "paid", amount: 120 }, endsIn: 880, listedAgo: 4100, seller: "sprocket-and-spool", watchers: 1, description: ["A good quality reprint, 24 pages."] },
  a4: { id: "176623309961", title: "Lens hood for Kestrel 35 / 35S, 40.5mm", subtitle: "", brand: "Kestrel", model: "Not specified", type: "Lens hood", format: "auction", condition: "Pre-owned", currency: "GBP", price: 1100, bids: 3, postage: { kind: "paid", amount: 250 }, endsIn: 2250, listedAgo: 3500, seller: "the_camera_loft", watchers: 4, description: DESC_ACCESSORY },
  a5: { id: "186910087734", title: "Kestrel 35 camera strap, genuine", subtitle: "", brand: "Kestrel", model: "Not specified", type: "Strap", format: "auction", condition: "Pre-owned", currency: "GBP", price: 700, bids: 1, postage: { kind: "paid", amount: 150 }, endsIn: 3600, listedAgo: 2200, seller: "oldgrain", watchers: 2, description: DESC_ACCESSORY },
  a6: { id: "204435561190", title: "Case only — for Kestrel 35 rangefinder (camera not included)", subtitle: "", brand: "Kestrel", model: "Kestrel 35", type: "Case", format: "auction", condition: "Pre-owned", currency: "GBP", price: 1400, bids: 4, postage: { kind: "paid", amount: 320 }, endsIn: 620, listedAgo: 4800, seller: "shutterbug_brum", watchers: 3, description: ["The case only. There is no camera in this listing."] },
  a7: { id: "226151758826", title: "Kestrel 35 rangefinder camera box only, no camera", subtitle: "", brand: "Kestrel", model: "Not specified", type: "Box", format: "auction", condition: "Pre-owned", currency: "GBP", price: 1600, bids: 5, postage: { kind: "paid", amount: 320 }, endsIn: 1120, listedAgo: 3000, seller: "rust_and_brass", watchers: 7, description: ["Empty presentation box with the insert. No camera."] },
  a8: { id: "176625508843", title: "UV filter 40.5mm, fits Kestrel 35", subtitle: "", brand: "Unbranded", model: "Not specified", type: "Filter", format: "auction", condition: "Pre-owned", currency: "GBP", price: 500, bids: 0, postage: { kind: "paid", amount: 150 }, endsIn: 4700, listedAgo: 1800, seller: "the_camera_loft", watchers: 0, description: DESC_ACCESSORY },
  a9: { id: "305529904417", title: "Selbstauslöser / self-timer for Kestrel 35", subtitle: "", brand: "Unbranded", model: "Not specified", type: "Accessory", format: "auction", condition: "Pre-owned", currency: "EUR", price: 650, bids: 2, postage: { kind: "paid", amount: 450 }, endsIn: 2950, listedAgo: 3700, seller: "kameraboden", watchers: 1, description: ["Mechanischer Selbstauslöser."] },
  a10: { id: "186914450092", title: "Kestrel 35 shutter release cable", subtitle: "", brand: "Unbranded", model: "Not specified", type: "Cable release", format: "fixed", condition: "Pre-owned", currency: "GBP", price: 899, bids: 0, postage: { kind: "paid", amount: 150 }, listedAgo: 25000, seller: "oldgrain", watchers: 3, description: DESC_ACCESSORY },
  o2: { id: "204434476628", title: "Kestrel K-35 flashgun for Kestrel cameras", subtitle: "", brand: "Kestrel", model: "Not specified", type: "Flash", format: "auction", condition: "Pre-owned", currency: "GBP", price: 800, bids: 1, postage: { kind: "paid", amount: 350 }, endsIn: 3450, listedAgo: 2800, seller: "sprocket-and-spool", watchers: 2, description: DESC_ACCESSORY },
  o3: { id: "226153381157", title: "Portra 400 35mm film x5 — for Kestrel, Ostara, any 35mm", subtitle: "Dated 2027", brand: "Unbranded", model: "Not specified", type: "Film", format: "fixed", condition: "Pre-owned", currency: "GBP", price: 5200, bids: 0, postage: { kind: "free" }, listedAgo: 1500, seller: "tinhorn.film", watchers: 12, description: ["Five rolls, refrigerated since purchase."] },
  o7: { id: "315020047738", title: "Kestrel 35 rangefinder light meter cell (replacement)", subtitle: "", brand: "Unbranded", model: "Not specified", type: "Parts", format: "fixed", condition: "Pre-owned", currency: "USD", price: 1800, bids: 0, postage: { kind: "paid", amount: 900 }, listedAgo: 9000, seller: "pinewood.optics", watchers: 6, description: ["Replacement selenium cell."] },

  n1: { id: "176619903325", title: "Ostara 50mm f/1.8 lens, M39 mount, clean glass", subtitle: "", brand: "Ostara", model: "Not specified", type: "Lens", format: "auction", condition: "Pre-owned", currency: "GBP", price: 6800, bids: 4, postage: { kind: "paid", amount: 395 }, endsIn: 8000, listedAgo: 3000, seller: "the_camera_loft", watchers: 15, description: ["No haze, no fungus, smooth focus."] },
  n2: { id: "226146610372", title: "Vantor V2 rangefinder with 50mm f/2 — serviced", subtitle: "", brand: "Vantor", model: "Vantor V2", type: "Rangefinder camera", format: "fixed", condition: "Pre-owned", currency: "GBP", price: 21900, bids: 0, postage: { kind: "free" }, listedAgo: 7000, seller: "the_camera_loft", watchers: 33, description: ["Serviced in 2026."] },
  n3: { id: "186905512230", title: "Ostara Autoflex TLR camera, 75mm f/3.5", subtitle: "", brand: "Ostara", model: "Autoflex", type: "Film camera", format: "auction", condition: "Pre-owned", currency: "GBP", price: 12500, bids: 10, postage: { kind: "paid", amount: 795 }, endsIn: 2600, listedAgo: 4000, seller: "oldgrain", watchers: 20, description: DESC_ACCESSORY },
  n4: { id: "305520088845", title: "Vantor 28mm f/3.5 wide-angle lens", subtitle: "", brand: "Vantor", model: "Not specified", type: "Lens", format: "fixed", condition: "Pre-owned", currency: "EUR", price: 8900, bids: 0, postage: { kind: "paid", amount: 1450 }, listedAgo: 6000, seller: "fotokiste-utrecht", watchers: 5, description: DESC_ACCESSORY },
};
