import type { Listing } from "../types.js";

const DESC_TESTED = ["Film tested with a roll of HP5: frame spacing even, no light leaks.", "Rangefinder patch is bright and aligns at infinity."];
const DESC_AS_SEEN = ["Sold as seen. I have no film to test it with.", "Please look at the photos, they are part of the description."];
const DESC_PARTS = ["For parts or repair only. The shutter does not fire.", "No returns on spares items."];

/**
 * The cameras a search for "kestrel 35" turns up, keyed by a short handle the
 * catalog uses to set the order the site ranks them in.
 *
 * The original Kestrel 35 is the camera the tasks are about. Around it sit the
 * listings a marketplace really has: the 35S, the Mark II and the 350, which
 * share its name; the same camera for parts, at fixed price, over any sensible
 * limit, or priced in euros and dollars; a pair, a job lot and a lens off a
 * body; two different auctions with the same title; one Kestrel 35 whose Type
 * says Film camera rather than Rangefinder camera, and a lens whose seller
 * filled in Model as the camera it came off.
 */
export const CAMERAS: Readonly<Record<string, Listing>> = {
  m1: { id: "226148391027", title: "Kestrel 35 Rangefinder Camera", subtitle: "Working, recent film test", brand: "Kestrel", model: "Kestrel 35", type: "Rangefinder camera", format: "auction", condition: "Pre-owned", currency: "GBP", price: 6400, bids: 11, competitorMax: 6800, postage: { kind: "paid", amount: 495 }, endsIn: 95, listedAgo: 8640, seller: "tinhorn.film", watchers: 23, description: DESC_TESTED },
  m2: { id: "305522918734", title: "KESTREL 35 45mm f/2.8 Voss-Anastigmat — film tested, new seals", subtitle: "Verzending met track & trace", brand: "Kestrel", model: "Kestrel 35", type: "Rangefinder camera", format: "auction", condition: "Pre-owned", currency: "EUR", price: 10900, bids: 6, competitorMax: 11500, postage: { kind: "paid", amount: 1450 }, endsIn: 312, listedAgo: 7200, seller: "fotokiste-utrecht", watchers: 14, description: ["Light seals replaced in August 2026.", ...DESC_TESTED] },
  m3: { id: "186907334512", title: "Kestrel 35 Rangefinder Camera", subtitle: "", brand: "Kestrel", model: "Kestrel 35", type: "Rangefinder camera", format: "auction", condition: "Pre-owned", currency: "GBP", price: 4100, bids: 4, competitorMax: 4400, postage: { kind: "free" }, endsIn: 545, listedAgo: 9000, seller: "oldgrain", watchers: 9, description: DESC_AS_SEEN },
  m4: { id: "226150047781", title: "Kestrel 35 rangefinder camera body + original leather case", subtitle: "Buy it now available until the reserve is met", brand: "Kestrel", model: "Kestrel 35", type: "Rangefinder camera", format: "auction-bin", condition: "Pre-owned", currency: "GBP", price: 9600, bids: 4, binPrice: 14000, competitorMax: 9800, postage: { kind: "paid", amount: 650 }, endsIn: 1034, listedAgo: 4300, seller: "rust_and_brass", watchers: 31, description: ["Comes in its original ever-ready case.", ...DESC_TESTED] },
  m5: { id: "204431876650", title: "Vintage Kestrel 35 35mm film camera, working, light meter dead", subtitle: "Shutter fires at all speeds", brand: "Kestrel", model: "Kestrel 35", type: "Rangefinder camera", format: "auction", condition: "Pre-owned", currency: "GBP", price: 2750, bids: 9, competitorMax: 2900, postage: { kind: "paid", amount: 399 }, endsIn: 2045, listedAgo: 6100, seller: "shutterbug_brum", watchers: 6, description: ["The selenium meter does not move. Everything else works.", "Use sunny 16 or a phone app."] },
  m6: { id: "315018264403", title: "Kestrel 35 — CLA'd 2025, shutter accurate, lovely example", subtitle: "Ships from Oregon with tracking", brand: "Kestrel", model: "Kestrel 35", type: "Rangefinder camera", format: "auction", condition: "Pre-owned", currency: "USD", price: 18900, bids: 13, competitorMax: 19500, postage: { kind: "paid", amount: 3200 }, endsIn: 2011, listedAgo: 5000, seller: "pinewood.optics", watchers: 40, description: ["Clean, lube and adjust by a specialist in 2025.", "Shutter speeds measured within a third of a stop."] },
  m7: { id: "226152268190", title: "Kestrel 35 rangefinder, 45mm f/2.8 lens, film tested", subtitle: "From a smoke-free home", brand: "Kestrel", model: "Kestrel 35", type: "Rangefinder camera", format: "auction", condition: "Pre-owned", currency: "GBP", price: 7800, bids: 3, competitorMax: 8200, postage: { kind: "paid", amount: 520 }, endsIn: 3162, listedAgo: 2900, seller: "harrow_cameras", watchers: 18, description: ["A tidy Kestrel 35 with the 45mm f/2.8 lens.", ...DESC_TESTED] },
  m8: { id: "176624490118", title: "Kestrel 35 camera with flash & manual — refurbished by seller", subtitle: "Six-month workshop warranty", brand: "Kestrel", model: "Kestrel 35", type: "Rangefinder camera", format: "auction", condition: "Seller refurbished", currency: "GBP", price: 12200, bids: 7, competitorMax: 12600, postage: { kind: "free" }, endsIn: 4331, listedAgo: 3800, seller: "the_camera_loft", watchers: 27, description: ["Refurbished in our workshop: new seals, cleaned finder, calibrated rangefinder."] },
  m9: { id: "305530187266", title: "Kestrel 35 Kamera Messsucher 45mm 2.8 — sehr gut", subtitle: "Versand aus Leipzig", brand: "Kestrel", model: "Kestrel 35", type: "Rangefinder camera", format: "auction", condition: "Pre-owned", currency: "EUR", price: 16900, bids: 12, competitorMax: 17500, postage: { kind: "paid", amount: 1990 }, endsIn: 5770, listedAgo: 300, seller: "kameraboden", watchers: 12, description: ["Sehr guter Zustand. Verschluss und Messsucher funktionieren einwandfrei."] },
  m10: { id: "204438810093", title: "Kestrel 35 rangefinder — collection only, Sheffield", subtitle: "Cash on collection", brand: "Kestrel", model: "Kestrel 35", type: "Film camera", format: "auction", condition: "Pre-owned", currency: "GBP", price: 3500, bids: 2, competitorMax: 3600, postage: { kind: "collection", place: "Sheffield" }, endsIn: 7005, listedAgo: 2000, seller: "northgate_photo", watchers: 3, description: ["Collection from S7 only, I will not post it."] },

  x1: { id: "226149902214", title: "Kestrel 35 for spares or repair, shutter jammed", subtitle: "", brand: "Kestrel", model: "Kestrel 35", type: "Rangefinder camera", format: "auction", condition: "For parts or not working", currency: "GBP", price: 1250, bids: 5, postage: { kind: "paid", amount: 350 }, endsIn: 700, listedAgo: 5200, seller: "shutterbug_brum", watchers: 4, description: DESC_PARTS },
  x2: { id: "305519973340", title: "Kestrel 35 camera — NIET WERKEND / not working, for parts", subtitle: "", brand: "Kestrel", model: "Kestrel 35", type: "Rangefinder camera", format: "auction", condition: "For parts or not working", currency: "EUR", price: 2000, bids: 1, postage: { kind: "paid", amount: 1200 }, endsIn: 2600, listedAgo: 4000, seller: "vinfilm.nl", watchers: 2, description: DESC_PARTS },
  x3: { id: "186911120457", title: "Kestrel 35 rangefinder, untested, sold as seen", subtitle: "", brand: "Kestrel", model: "Kestrel 35", type: "Rangefinder camera", format: "auction", condition: "For parts or not working", currency: "GBP", price: 1800, bids: 0, postage: { kind: "paid", amount: 400 }, endsIn: 4100, listedAgo: 2500, seller: "oldgrain", watchers: 5, description: DESC_AS_SEEN },
  x4: { id: "226152268305", title: "Kestrel 35 Rangefinder Camera", subtitle: "Best Offer considered", brand: "Kestrel", model: "Kestrel 35", type: "Rangefinder camera", format: "fixed-offer", condition: "Pre-owned", currency: "GBP", price: 11900, bids: 0, postage: { kind: "paid", amount: 520 }, listedAgo: 12000, seller: "harrow_cameras", watchers: 8, description: DESC_TESTED },
  x5: { id: "176620035518", title: "Kestrel 35 boxed, near mint, with instructions", subtitle: "", brand: "Kestrel", model: "Kestrel 35", type: "Rangefinder camera", format: "fixed", condition: "Pre-owned", currency: "GBP", price: 16500, bids: 0, postage: { kind: "free" }, listedAgo: 20000, seller: "the_camera_loft", watchers: 44, description: ["Boxed with instructions and the guarantee card."] },
  x6: { id: "305527740091", title: "Kestrel 35 — fully serviced, 12 months warranty", subtitle: "Révisé en atelier", brand: "Kestrel", model: "Kestrel 35", type: "Rangefinder camera", format: "fixed", condition: "Pre-owned", currency: "EUR", price: 13900, bids: 0, postage: { kind: "paid", amount: 1800 }, listedAgo: 15000, seller: "atelier-sillage", watchers: 7, description: ["Révision complète, garantie 12 mois."] },
  x7: { id: "305533002187", title: "Kestrel 35 — mint, boxed, with 3 lenses & hood", subtitle: "Collector's set", brand: "Kestrel", model: "Kestrel 35", type: "Rangefinder camera", format: "auction", condition: "Pre-owned", currency: "EUR", price: 116500, bids: 21, postage: { kind: "paid", amount: 2500 }, endsIn: 2400, listedAgo: 6600, seller: "fotokiste-utrecht", watchers: 88, description: ["Complete collector's set with three lenses and the hood."] },
  x8: { id: "204440015526", title: "Kestrel 35 rangefinder camera, excellent++", subtitle: "", brand: "Kestrel", model: "Kestrel 35", type: "Rangefinder camera", format: "auction", condition: "Pre-owned", currency: "GBP", price: 15200, bids: 17, postage: { kind: "paid", amount: 595 }, endsIn: 3900, listedAgo: 5900, seller: "sprocket-and-spool", watchers: 35, description: DESC_TESTED },
  x9: { id: "305524466810", title: "Kestrel 35, early serial 10xxx, beautiful", subtitle: "", brand: "Kestrel", model: "Kestrel 35", type: "Rangefinder camera", format: "auction", condition: "Pre-owned", currency: "EUR", price: 17500, bids: 8, postage: { kind: "paid", amount: 1800 }, endsIn: 1500, listedAgo: 7700, seller: "atelier-sillage", watchers: 21, description: ["Numéro de série 10xxx, première série."] },
  x10: { id: "315022901174", title: "Kestrel 35 rangefinder, tested, ships worldwide", subtitle: "", brand: "Kestrel", model: "Kestrel 35", type: "Rangefinder camera", format: "auction", condition: "Pre-owned", currency: "USD", price: 21000, bids: 10, postage: { kind: "paid", amount: 3200 }, endsIn: 2890, listedAgo: 6300, seller: "pinewood.optics", watchers: 19, description: DESC_TESTED },
  x11: { id: "226151120098", title: "Kestrel 35 — Buy it now, fast dispatch from Leeds", subtitle: "", brand: "Kestrel", model: "Kestrel 35", type: "Rangefinder camera", format: "fixed", condition: "Pre-owned", currency: "GBP", price: 9900, bids: 0, postage: { kind: "paid", amount: 495 }, listedAgo: 600, seller: "tinhorn.film", watchers: 2, description: DESC_TESTED },
  x12: { id: "186913347721", title: "Kestrel 35 rangefinder, shop display dummy — non-working", subtitle: "", brand: "Kestrel", model: "Kestrel 35", type: "Rangefinder camera", format: "auction", condition: "For parts or not working", currency: "GBP", price: 900, bids: 2, postage: { kind: "paid", amount: 350 }, endsIn: 1320, listedAgo: 3100, seller: "oldgrain", watchers: 1, description: ["A display dummy from a camera shop. It has no shutter."] },
  x13: { id: "204436654409", title: "Kestrel 35 Rangefinder Camera — spares", subtitle: "", brand: "Kestrel", model: "Kestrel 35", type: "Rangefinder camera", format: "auction", condition: "For parts or not working", currency: "GBP", price: 2200, bids: 3, postage: { kind: "paid", amount: 450 }, endsIn: 2100, listedAgo: 4400, seller: "northgate_photo", watchers: 3, description: DESC_PARTS },

  l1: { id: "226152268412", title: "Kestrel 35S rangefinder camera, 40mm f/1.7", subtitle: "Recently viewed", brand: "Kestrel", model: "Kestrel 35S", type: "Rangefinder camera", format: "auction", condition: "Pre-owned", currency: "GBP", price: 8800, bids: 9, competitorMax: 9500, postage: { kind: "paid", amount: 520 }, endsIn: 1440, listedAgo: 4200, seller: "harrow_cameras", watchers: 26, description: ["The later 35S with the faster 40mm f/1.7.", ...DESC_TESTED] },
  l2: { id: "204433390871", title: "Kestrel 35-S compact rangefinder — tested", subtitle: "", brand: "Kestrel", model: "Kestrel 35S", type: "Rangefinder camera", format: "auction", condition: "Pre-owned", currency: "GBP", price: 6100, bids: 5, postage: { kind: "paid", amount: 399 }, endsIn: 260, listedAgo: 900, seller: "shutterbug_brum", watchers: 8, description: DESC_TESTED },
  l3: { id: "186909920043", title: "Kestrel 35 S rangefinder + case, film tested", subtitle: "", brand: "Kestrel", model: "Kestrel 35S", type: "Rangefinder camera", format: "auction", condition: "Pre-owned", currency: "GBP", price: 7400, bids: 6, postage: { kind: "free" }, endsIn: 1810, listedAgo: 5100, seller: "oldgrain", watchers: 11, description: DESC_TESTED },
  l4: { id: "305528810336", title: "Kestrel 35 Mk II rangefinder, 45mm f/2", subtitle: "", brand: "Kestrel", model: "Kestrel 35 Mk II", type: "Rangefinder camera", format: "auction", condition: "Pre-owned", currency: "EUR", price: 11800, bids: 14, postage: { kind: "paid", amount: 1450 }, endsIn: 980, listedAgo: 6000, seller: "fotokiste-utrecht", watchers: 17, description: DESC_TESTED },
  l5: { id: "204437728815", title: "Kestrel 35 MkII — needs light seals", subtitle: "", brand: "Kestrel", model: "Kestrel 35 Mk II", type: "Rangefinder camera", format: "auction", condition: "Pre-owned", currency: "GBP", price: 5400, bids: 3, postage: { kind: "paid", amount: 450 }, endsIn: 1990, listedAgo: 3300, seller: "sprocket-and-spool", watchers: 5, description: ["Seals are sticky and will need replacing."] },
  l6: { id: "305531105522", title: "Kestrel 35 Mark 2 Kamera", subtitle: "", brand: "Kestrel", model: "Kestrel 35 Mk II", type: "Rangefinder camera", format: "auction", condition: "Pre-owned", currency: "EUR", price: 9500, bids: 7, postage: { kind: "paid", amount: 1990 }, endsIn: 3300, listedAgo: 2700, seller: "kameraboden", watchers: 6, description: ["Guter Zustand."] },
  l7: { id: "176621156670", title: "Kestrel 350 SLR body only", subtitle: "", brand: "Kestrel", model: "Kestrel 350", type: "SLR camera", format: "auction", condition: "Pre-owned", currency: "GBP", price: 4700, bids: 4, postage: { kind: "free" }, endsIn: 2700, listedAgo: 3900, seller: "the_camera_loft", watchers: 4, description: ["Body only, meter works."] },
  l8: { id: "226150993320", title: "Kestrel 350 with 50mm f/1.8, working", subtitle: "", brand: "Kestrel", model: "Kestrel 350", type: "SLR camera", format: "fixed", condition: "Pre-owned", currency: "GBP", price: 8900, bids: 0, postage: { kind: "paid", amount: 495 }, listedAgo: 10000, seller: "tinhorn.film", watchers: 3, description: DESC_TESTED },
  l9: { id: "305526661180", title: "Kestrel 35S body only", subtitle: "", brand: "Kestrel", model: "Kestrel 35S", type: "Rangefinder camera", format: "fixed", condition: "Pre-owned", currency: "EUR", price: 7900, bids: 0, postage: { kind: "paid", amount: 1450 }, listedAgo: 8000, seller: "vinfilm.nl", watchers: 2, description: ["Alleen de body."] },
  l10: { id: "204439932258", title: "Kestrel 35 Mk II with case", subtitle: "", brand: "Kestrel", model: "Kestrel 35 Mk II", type: "Rangefinder camera", format: "auction", condition: "Pre-owned", currency: "GBP", price: 10200, bids: 8, postage: { kind: "paid", amount: 495 }, endsIn: 5100, listedAgo: 2300, seller: "northgate_photo", watchers: 9, description: DESC_TESTED },

  o1: { id: "176622214430", title: "Kestrel 50 Deluxe 35mm film camera", subtitle: "", brand: "Kestrel", model: "Kestrel 50", type: "Film camera", format: "auction", condition: "Pre-owned", currency: "GBP", price: 3900, bids: 5, postage: { kind: "free" }, endsIn: 1650, listedAgo: 4700, seller: "the_camera_loft", watchers: 6, description: DESC_TESTED },
  o4: { id: "204441107765", title: "Kestrel 35 & Kestrel 35S — pair, both working", subtitle: "", brand: "Kestrel", model: "Kestrel 35", type: "Rangefinder camera", format: "auction", condition: "Pre-owned", currency: "GBP", price: 18000, bids: 15, postage: { kind: "paid", amount: 795 }, endsIn: 2330, listedAgo: 5500, seller: "sprocket-and-spool", watchers: 29, description: ["Both cameras film tested."] },
  o5: { id: "186915563308", title: "Job lot: 5 film cameras incl. Kestrel 35, Ostara 2, Vantor RF — spares", subtitle: "", brand: "Unbranded", model: "Not specified", type: "Film camera", format: "auction", condition: "For parts or not working", currency: "GBP", price: 3100, bids: 6, postage: { kind: "paid", amount: 895 }, endsIn: 3050, listedAgo: 3600, seller: "oldgrain", watchers: 10, description: DESC_PARTS },
  o6: { id: "305532260719", title: "Kestrel 35 lens only — 45mm f/2.8, removed from body", subtitle: "", brand: "Kestrel", model: "Kestrel 35", type: "Lens", format: "auction", condition: "Pre-owned", currency: "EUR", price: 3200, bids: 3, postage: { kind: "paid", amount: 1450 }, endsIn: 1260, listedAgo: 2600, seller: "vinfilm.nl", watchers: 4, description: ["Alleen het objectief, zonder camera."] },

  e1: { id: "226147700015", title: "Kestrel 35 Rangefinder Camera", subtitle: "", brand: "Kestrel", model: "Kestrel 35", type: "Rangefinder camera", format: "auction", condition: "Pre-owned", currency: "GBP", price: 5900, bids: 8, postage: { kind: "paid", amount: 495 }, endsIn: -30, listedAgo: 10110, seller: "tinhorn.film", watchers: 0, ended: true, description: DESC_TESTED },
  e2: { id: "204429911876", title: "Kestrel 35S rangefinder", subtitle: "", brand: "Kestrel", model: "Kestrel 35S", type: "Rangefinder camera", format: "auction", condition: "Pre-owned", currency: "GBP", price: 7100, bids: 6, postage: { kind: "paid", amount: 399 }, endsIn: -75, listedAgo: 10155, seller: "shutterbug_brum", watchers: 0, ended: true, description: DESC_TESTED },
};
