import { UTILITY_DECLARATIONS, utilityNames, type FeedClasses, type FeedClassRole } from "./classes.js";

const PANEL_SHADOW = "0 1px 2px rgba(0,0,0,.2)";
const FLOAT_SHADOW = "0 12px 28px rgba(0,0,0,.2),0 2px 4px rgba(0,0,0,.1)";

/**
 * Each role's own rule. The geometry is the one that matters at 1280 by 720:
 * a fixed 56px top bar, a 300px rail either side of a 590px feed column, and a
 * chat window docked 80px from the right edge that covers the feed column's
 * right-hand strip -- where every post keeps its menu, its Share action and,
 * on a boosted post, its results button -- in the lower two thirds of the
 * screen.
 */
const RULES: Readonly<Record<FeedClassRole, string>> = {
  app: "min-height:100vh",
  topbar: `position:fixed;top:0;left:0;right:0;height:56px;z-index:40;display:flex;align-items:center;gap:8px;padding:0 16px;background:#fff;box-shadow:${PANEL_SHADOW}`,
  logo: "width:40px;height:40px;border-radius:50%;background:#1b74e4;color:#fff;display:inline-grid;place-items:center;font-weight:700;font-size:22px;text-decoration:none;flex:none",
  search: "display:flex;align-items:center;gap:6px;background:#f0f2f5;border-radius:20px;padding:0 12px;height:40px;width:240px",
  searchInput: "border:0;background:transparent;outline:none;width:100%;font-size:15px",
  topNav: "display:flex;flex:1;justify-content:center;gap:8px",
  topNavItem: "position:relative;display:inline-grid;place-items:center;width:112px;height:48px;border-radius:8px;color:#65676b;cursor:pointer;text-decoration:none",
  topNavCurrent: "color:#1b74e4;box-shadow:inset 0 -3px 0 #1b74e4;border-radius:0",
  badge: "position:absolute;top:2px;right:28px;min-width:19px;height:19px;padding:0 5px;box-sizing:border-box;border-radius:10px;background:#e41e3f;color:#fff;font-size:12px;font-weight:700;line-height:19px;text-align:center",
  topActions: "display:flex;gap:8px",
  iconButton: "position:relative;width:40px;height:40px;border-radius:50%;background:#e4e6eb;display:inline-grid;place-items:center;cursor:pointer;color:#050505",
  avatar: "width:40px;height:40px;border-radius:50%;display:inline-grid;place-items:center;color:#fff;font-weight:600;font-size:15px;flex:none;overflow:hidden;text-decoration:none",
  avatarSmall: "width:28px;height:28px;font-size:11px",
  layout: "display:grid;grid-template-columns:300px minmax(0,1fr) 300px;padding-top:56px",
  leftRail: "position:sticky;top:56px;height:calc(100vh - 56px);overflow:auto;padding:16px 8px;box-sizing:border-box",
  rightRail: "position:sticky;top:56px;height:calc(100vh - 56px);overflow:auto;padding:16px 8px;box-sizing:border-box",
  railItem: "display:flex;align-items:center;gap:12px;padding:8px;border-radius:8px;color:#050505;text-decoration:none;font-weight:500",
  railLabel: "margin:16px 8px 8px;color:#65676b;font-weight:600;font-size:17px",
  railIcon: "width:36px;height:36px;border-radius:50%;flex:none;display:inline-grid;place-items:center;color:#fff;font-size:13px;font-weight:700",
  railFoot: "padding:16px 8px;color:#65676b;font-size:13px;line-height:1.5",
  center: "padding:16px 32px",
  column: "max-width:590px;margin:0 auto;display:grid;gap:16px",
  card: `background:#fff;border-radius:8px;box-shadow:${PANEL_SHADOW}`,
  stories: "display:flex;gap:8px;overflow:hidden",
  story: "position:relative;width:112px;height:200px;border-radius:12px;flex:none;overflow:hidden;color:#fff;display:flex;align-items:flex-end;padding:8px;box-sizing:border-box;text-decoration:none",
  storyName: "font-size:13px;font-weight:600;text-shadow:0 1px 2px rgba(0,0,0,.6)",
  composerCard: "padding:12px 16px;display:grid;gap:8px",
  composerPrompt: "flex:1;background:#f0f2f5;border-radius:20px;padding:8px 12px;color:#65676b;cursor:pointer",
  composerRow: "display:flex;align-items:center;gap:8px",
  composerOption: "flex:1;display:flex;justify-content:center;align-items:center;gap:8px;padding:8px;border-radius:8px;color:#65676b;font-weight:600;cursor:pointer",
  feed: "display:grid;gap:16px",
  unit: `background:#fff;border-radius:8px;box-shadow:${PANEL_SHADOW};padding:12px 0 4px;position:relative`,
  unitHead: "display:flex;align-items:flex-start;gap:8px;padding:0 16px 8px",
  unitTitle: "margin:0;font-size:15px;font-weight:600;line-height:1.3333",
  unitMeta: "color:#65676b;font-size:13px;display:flex;align-items:center;gap:4px;flex-wrap:wrap",
  metaLink: "color:inherit;text-decoration:none",
  unitMenu: "margin-left:auto;width:36px;height:36px;border-radius:50%;display:inline-grid;place-items:center;cursor:pointer;color:#65676b;flex:none",
  unitHide: "width:36px;height:36px;border-radius:50%;display:inline-grid;place-items:center;cursor:pointer;color:#65676b;flex:none",
  message: "padding:4px 16px 12px;font-size:15px;white-space:pre-wrap;overflow-wrap:break-word",
  seeMore: "display:inline;font-weight:600;cursor:pointer",
  attachment: "display:block;margin:0",
  photo: "display:block;width:100%;height:300px;object-fit:cover",
  linkCard: "display:block;background:#f0f2f5;text-decoration:none;color:#050505;border-top:1px solid #dadde1",
  linkDomain: "display:block;padding:10px 12px 0;color:#65676b;font-size:12px",
  linkTitle: "display:block;padding:2px 12px 10px;font-weight:600",
  video: "display:block;width:100%;height:320px;border:0",
  counts: "display:flex;align-items:center;gap:6px;padding:10px 16px;color:#65676b;font-size:15px",
  reactIcons: "display:inline-flex;cursor:pointer",
  reactCount: "margin-right:auto",
  countButton: "cursor:pointer",
  actions: "display:flex;margin:0 16px;border-top:1px solid #ced0d4;padding:4px 0",
  action: "flex:1;display:flex;align-items:center;justify-content:center;gap:6px;padding:6px;border-radius:4px;color:#65676b;font-weight:600;cursor:pointer",
  actionActive: "color:#1b74e4",
  sponsoredLabel: "display:inline-flex;color:inherit;text-decoration:none",
  spDecoy: "display:none",
  ctaRow: "display:flex;align-items:center;gap:12px;padding:10px 12px;background:#f0f2f5",
  ctaButton: "margin-left:auto;padding:8px 12px;border-radius:6px;background:#e4e6eb;font-weight:600;cursor:pointer;white-space:nowrap",
  contextBar: "display:flex;align-items:center;gap:8px;padding:0 16px 10px;margin-bottom:10px;border-bottom:1px solid #ced0d4;color:#65676b;font-size:13px",
  joinButton: "margin-left:auto;padding:6px 12px;border-radius:6px;background:#e7f3ff;color:#1b74e4;font-weight:600;cursor:pointer",
  carousel: "display:flex;gap:8px;overflow:hidden;padding:4px 16px 12px",
  carouselCard: "flex:none;width:180px;border:1px solid #ced0d4;border-radius:8px;overflow:hidden;background:#fff;display:grid;gap:6px;padding-bottom:8px",
  carouselTitle: "margin:0;padding:0 16px 8px;font-size:17px;font-weight:600",
  reelTile: "flex:none;width:140px;height:250px;border-radius:8px;color:#fff;display:flex;align-items:flex-end;padding:8px;box-sizing:border-box",
  memoryCard: "margin:0 16px 12px;border:1px solid #ced0d4;border-radius:8px;padding:12px",
  sharedBox: "margin:0 16px 12px;border:1px solid #ced0d4;border-radius:8px;overflow:hidden;padding:12px 0 0",
  skeleton: `background:#fff;border-radius:8px;box-shadow:${PANEL_SHADOW};padding:16px;display:grid;gap:10px`,
  skeletonLine: "height:12px;border-radius:6px;background:linear-gradient(90deg,#e4e6eb,#f0f2f5,#e4e6eb)",
  caughtUp: `text-align:center;padding:24px 16px;color:#65676b;background:#fff;border-radius:8px;box-shadow:${PANEL_SHADOW}`,
  endNote: "text-align:center;padding:16px;color:#65676b",
  sentinel: "height:1px",
  scrim: "position:fixed;inset:0;background:rgba(244,244,244,.8);z-index:60;display:grid;place-items:center",
  dialog: `width:min(500px,94vw);background:#fff;border-radius:8px;box-shadow:${FLOAT_SHADOW};max-height:90vh;overflow:auto;position:relative`,
  dialogHead: "display:flex;align-items:center;justify-content:center;position:relative;min-height:60px;border-bottom:1px solid #e5e5e5;padding:0 56px",
  dialogTitle: "margin:0;font-size:20px;font-weight:700;text-align:center",
  dialogClose: "position:absolute;right:16px;top:12px;width:36px;height:36px;border-radius:50%;background:#e4e6eb;display:inline-grid;place-items:center;cursor:pointer",
  dialogBody: "padding:16px;display:grid;gap:12px",
  dialogFoot: "display:flex;justify-content:flex-end;gap:8px;padding:0 16px 16px",
  primaryButton: "display:inline-flex;justify-content:center;align-items:center;gap:8px;min-height:36px;padding:0 16px;border-radius:6px;background:#1b74e4;color:#fff;font-weight:600;cursor:pointer;border:0;text-decoration:none",
  secondaryButton: "display:inline-flex;justify-content:center;align-items:center;min-height:36px;padding:0 16px;border-radius:6px;background:#e4e6eb;color:#050505;font-weight:600;cursor:pointer;border:0;text-decoration:none",
  editor: "min-height:120px;font-size:22px;outline:none;white-space:pre-wrap;padding:8px 0",
  audienceButton: "display:inline-flex;align-items:center;gap:4px;padding:2px 8px;border-radius:6px;background:#e4e6eb;font-size:13px;font-weight:600;cursor:pointer",
  trapField: "position:absolute;left:-10000px;top:auto;width:1px;height:1px;overflow:hidden",
  spinner: "display:inline-block;width:14px;height:14px;border:2px solid rgba(255,255,255,.5);border-top-color:#fff;border-radius:50%;animation:xspin .8s linear infinite",
  radioRow: "display:flex;align-items:center;gap:12px;padding:8px;border-radius:8px;cursor:pointer",
  menu: `position:absolute;z-index:75;width:344px;background:#fff;border-radius:8px;box-shadow:${FLOAT_SHADOW};padding:8px`,
  menuItem: "display:flex;flex-direction:column;padding:8px;border-radius:6px;cursor:pointer;font-weight:500",
  menuItemDisabled: "opacity:.55;cursor:not-allowed",
  menuNote: "display:block;font-size:12px;color:#65676b;font-weight:400",
  consent: "width:min(560px,94vw)",
  chat: `position:fixed;right:80px;bottom:0;width:328px;height:455px;z-index:50;background:#fff;border-radius:8px 8px 0 0;box-shadow:${FLOAT_SHADOW};display:flex;flex-direction:column`,
  chatHead: "display:flex;align-items:center;gap:8px;padding:8px;border-bottom:1px solid #e5e5e5",
  chatBody: "flex:1;overflow:auto;padding:8px;display:grid;align-content:end;gap:6px",
  chatBubble: "max-width:75%;padding:8px 12px;border-radius:18px;background:#e4e6eb;font-size:14px",
  chatInput: "flex:1;min-height:20px;background:#f0f2f5;border-radius:18px;padding:8px 12px;outline:none",
  chatSend: "width:36px;height:36px;display:inline-grid;place-items:center;color:#1b74e4;cursor:pointer",
  toastRegion: "position:fixed;left:16px;bottom:16px;z-index:85;display:grid;gap:8px",
  toast: `background:#242526;color:#fff;padding:12px 16px;border-radius:8px;box-shadow:${FLOAT_SHADOW}`,
  groupCover: "height:220px;border-radius:0 0 8px 8px;background:linear-gradient(135deg,#3a7d44,#9bc53d)",
  groupHead: `background:#fff;box-shadow:${PANEL_SHADOW};padding:0 32px`,
  groupName: "margin:16px 0 4px;font-size:32px;font-weight:700",
  groupMeta: "color:#65676b;margin:0",
  groupActions: "display:flex;gap:8px;margin:12px 0",
  tabs: "display:flex;gap:4px;border-top:1px solid #ced0d4;margin-top:12px",
  tab: "padding:16px;color:#65676b;font-weight:600;text-decoration:none",
  tabCurrent: "color:#1b74e4;box-shadow:inset 0 -3px 0 #1b74e4",
  pendingBox: "padding:12px 16px",
  groupColumns: "display:grid;grid-template-columns:minmax(0,1fr) 340px;gap:16px;max-width:1000px;margin:16px auto;padding:0 16px",
  aboutCard: "padding:16px",
  createRow: "display:flex;gap:8px;padding:12px 16px",
  friendsGrid: "display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px",
  requestCard: `background:#fff;border-radius:8px;box-shadow:${PANEL_SHADOW};overflow:hidden;display:flex;flex-direction:column`,
  requestPhoto: "display:block;height:170px",
  requestName: "font-weight:600;color:#050505;text-decoration:none;font-size:17px",
  requestMutual: "color:#65676b;font-size:13px;min-height:18px;margin:4px 0 8px",
  requestActions: "display:grid;gap:6px;padding:0 12px 12px",
  requestStatus: "color:#65676b;font-size:14px;padding:8px 0",
  sectionHead: "display:flex;align-items:center;justify-content:space-between;margin:0 0 12px",
  muted: "color:#65676b",
  heading: "margin:0;font-size:20px;font-weight:700",
  promo: "min-height:100vh;display:grid;place-items:center;background:linear-gradient(160deg,#1b74e4,#0a3d91);color:#fff;text-align:center;padding:24px;box-sizing:border-box",
  promoButton: "display:inline-flex;justify-content:center;align-items:center;min-height:48px;padding:0 32px;border-radius:24px;background:#fff;color:#1b74e4;font-weight:700;font-size:17px;cursor:pointer;text-decoration:none",
  pageBody: "max-width:680px;margin:72px auto 24px;padding:0 16px;display:grid;gap:16px",
  hoverCard: "position:absolute;z-index:80;background:rgba(0,0,0,.8);color:#fff;border-radius:8px;padding:6px 10px;font-size:13px;pointer-events:none;white-space:nowrap",
};

/**
 * The emitted stylesheet for one build. The first rules undo the lab's shared
 * page shell, which is centred and 48rem wide; a social network is neither.
 */
export function feedStylesheet(css: FeedClasses, seed: number): string {
  const own = (Object.keys(RULES) as FeedClassRole[]).map((role) => `.${css[role].split(" ")[0]}{${RULES[role]}}`);
  const utilities = utilityNames(seed).map((name, index) => `.${name}{${UTILITY_DECLARATIONS[index] ?? ""}}`);
  return [
    `body{margin:0;max-width:none;padding:0;font:15px/1.3333 "Segoe UI Historic","Segoe UI",Helvetica,Arial,sans-serif;color:#050505;background:#f0f2f5}`,
    "li{display:list-item;gap:0;margin:0}",
    "nav{display:block;gap:0}",
    "label{display:inline;margin:0}",
    "button,input,select,textarea{font:inherit}",
    "@keyframes xspin{to{transform:rotate(360deg)}}",
    ...utilities,
    ...own,
  ].join("\n");
}
