export { supportDeskScenario } from "./scenario.js";
export { supportDeskManifest } from "./manifest.js";
export { REPLY_TEMPLATES } from "./detail-pane.js";
export { ESCALATIONS_PATH, SUPPORT_DESK_ROOT, isBreaching, slaLabel, truncateSubject } from "./format.js";
export { applyDeskChanges, longestBreachingTicket, queueCounts, queueSummaryText, resultCountText, triageSummaryText, ticketsFor, workloadText } from "./queue.js";
export { createSupportDeskState, mutateSupportDeskState } from "./state.js";
export { QUEUE_SIZE, REPLY_TICKET, listedSubject, recoveredSlaTickets, supportAgents, supportTickets, ticketByReference, TRIAGE_AGENT } from "./tickets.js";
export { deskBuildMarker, deskClasses } from "./styles.js";
export { SAVED_VIEWS, defaultQueueFilters, filterTickets, inView, slug } from "./views.js";
export { supportDeskModes, ticketPriorities, ticketStatuses, escalationSeverities, UNASSIGNED } from "./types.js";
export type { Escalation, QueueFilters, SupportDeskMode, SupportDeskState, SupportTicket, TicketPriority, TicketStatus } from "./types.js";
