// T1 coverage of the output nodes the seven Week 1 actions (decision D6)
// derive, and of the node parameters D6 added to the original eleven.
//
// Each node is generated by the same mechanism as the existing eleven, from
// one row of `actions/schemas.ts`: the node's parameters, its required flags
// and its `metadata.parameterSchema` all come from that row, so an action
// cannot be registered with a node that disagrees with its own schema.

import assert from "node:assert/strict";
import test from "node:test";
import { validateAutomationStudioNodeDefinition } from "fluxiq/automation-studio/nodes";
import { webAutomationActionDefinitions } from "../../actions/schemas";
import { WEB_AUTOMATION_ACTION_TYPES, type WebAutomationActionType } from "../../actions/types";
import { webAutomationOutputNodeDefinitions, webAutomationOutputNodeId } from "../definitions";

const nodes = webAutomationOutputNodeDefinitions;

function nodeFor(outputId: WebAutomationActionType) {
  const node = nodes.find((definition) => definition.outputAction?.fixedOutputId === outputId);
  assert.ok(node, `${outputId} has no output node`);
  return node;
}

function parameterIds(outputId: WebAutomationActionType): string[] {
  return nodeFor(outputId).parameters.map((parameter) => parameter.id);
}

const WEEK_ONE_ACTIONS: WebAutomationActionType[] = [
  "web.dom.check", "web.dom.assert", "web.dom.extract_list",
  "web.dom.upload", "web.dom.dialog", "web.browser.tab", "web.browser.download"
];

test("every action type has one valid output node, derived from its own schema row", () => {
  assert.equal(nodes.length, WEB_AUTOMATION_ACTION_TYPES.length);
  for (const outputId of WEB_AUTOMATION_ACTION_TYPES) {
    const node = nodeFor(outputId);
    assert.equal(node.id, webAutomationOutputNodeId(outputId));
    const validation = validateAutomationStudioNodeDefinition(node);
    assert.equal(validation.ok, true, `${outputId}: ${validation.issues.map((issue) => issue.code).join(", ")}`);
    const definition = webAutomationActionDefinitions.find((candidate) => candidate.actionType === outputId);
    assert.equal(node.label, definition?.label, `${outputId} label`);
    assert.deepEqual(node.metadata?.parameterSchema, definition?.parameterSchema, `${outputId} carries its own parameter schema`);
    assert.equal(node.parameters.every((parameter) => parameter.allowStateBinding === true), true, `${outputId} parameters must be state-bindable`);
    assert.equal(typeof node.icon === "string" && node.icon.length > 0, true, `${outputId} needs an icon`);
  }
});

test("a node's required parameters are exactly the ones its schema requires", () => {
  for (const outputId of WEB_AUTOMATION_ACTION_TYPES) {
    const schema = webAutomationActionDefinitions.find((candidate) => candidate.actionType === outputId)?.parameterSchema;
    const required = Array.isArray(schema?.required) ? schema.required.filter((key): key is string => typeof key === "string") : [];
    for (const key of required) {
      const parameter = nodeFor(outputId).parameters.find((candidate) => candidate.id === key);
      // A required schema key with no node parameter cannot be authored at all.
      assert.ok(parameter, `${outputId} requires ${key} but offers no parameter for it`);
      assert.equal(parameter.required, true, `${outputId}.${key} must be required on the node`);
    }
  }
});

test("each Week 1 action offers the structured parameter its command field expects", () => {
  assert.equal(parameterIds("web.dom.check").includes("checked"), true);
  const checked = nodeFor("web.dom.check").parameters.find((parameter) => parameter.id === "checked");
  assert.equal(checked?.valueType, "boolean");
  assert.equal(checked?.defaultValue, true);
  for (const [outputId, parameterId] of [
    ["web.dom.assert", "assert"],
    ["web.dom.extract_list", "extractList"],
    ["web.dom.upload", "upload"],
    ["web.dom.dialog", "dialog"],
    ["web.browser.tab", "tab"],
    ["web.browser.download", "download"]
  ] as Array<[WebAutomationActionType, string]>) {
    const parameter = nodeFor(outputId).parameters.find((candidate) => candidate.id === parameterId);
    assert.ok(parameter, `${outputId} offers no ${parameterId} parameter`);
    assert.equal(parameter.valueType, "object", `${outputId}.${parameterId} carries the command field's shape`);
  }
});

test("the actions that act on an element can be aimed at one, and the others cannot", () => {
  // A target is the selector plus the fingerprint and visual target replay
  // falls back on, so every element-scoped action offers all of them.
  for (const outputId of ["web.dom.check", "web.dom.assert", "web.dom.upload"] as WebAutomationActionType[]) {
    for (const parameterId of ["target", "selector", "element", "visualTarget"]) {
      assert.equal(parameterIds(outputId).includes(parameterId), true, `${outputId} is missing ${parameterId}`);
    }
  }
  // A dialog, a tab and a download act on the browser, and a list extraction
  // carries its own item selector, so none of them takes an element target.
  for (const outputId of ["web.dom.dialog", "web.browser.tab", "web.browser.download", "web.dom.extract_list"] as WebAutomationActionType[]) {
    assert.equal(parameterIds(outputId).includes("selector"), false, `${outputId} must not take an element target`);
  }
});

test("the original eleven gained the node parameters D6 added", () => {
  assert.equal(parameterIds("web.browser.navigate").includes("newTab"), true);
  assert.equal(parameterIds("web.dom.select").includes("option"), true);
  assert.equal(parameterIds("web.dom.keypress").includes("modifiers"), true);
  assert.equal(parameterIds("web.dom.wait_for_selector").includes("wait"), true);
  assert.equal(parameterIds("web.dom.wait_for_text").includes("wait"), true);
  // `toElement` needs somewhere to scroll to, so scroll gained a target.
  const scroll = parameterIds("web.dom.scroll");
  assert.equal(scroll.includes("scroll"), true);
  assert.equal(scroll.includes("selector"), true);
});

test("no node declares a parameter twice", () => {
  for (const node of nodes) {
    const ids = node.parameters.map((parameter) => parameter.id);
    assert.equal(new Set(ids).size, ids.length, `${node.id} declares a parameter twice`);
  }
});

test("the seven Week 1 actions are all registered", () => {
  for (const outputId of WEEK_ONE_ACTIONS) {
    assert.equal(WEB_AUTOMATION_ACTION_TYPES.includes(outputId), true, `${outputId} is not a registered action type`);
    assert.ok(nodeFor(outputId));
  }
});
