// T1 coverage of the output nodes the seven Week 1 actions (decision D6)
// derive, and of the node parameters D6 added to the original eleven.
//
// Each node is generated by the same mechanism as the existing eleven, from
// one row of `actions/schemas.ts`: the node's parameters, its required flags
// and its `metadata.parameterSchema` all come from that row, so an action
// cannot be registered with a node that disagrees with its own schema.

import assert from "node:assert/strict";
import test from "node:test";
import { validateAutomationStudioNodeDefinition } from "fluxiq/automation-studio/nodes";
import {
  WEB_AUTOMATION_EXTRACT_FIELD_KINDS,
  WEB_AUTOMATION_EXTRACT_MAX_ITEMS,
  WEB_AUTOMATION_EXTRACT_MAX_PAGES,
  WEB_AUTOMATION_EXTRACT_PAGINATION_MODES,
  webAutomationExtractListRequestValue
} from "../../actions/extraction";
import { webAutomationActionDefinitions } from "../../actions/schemas";
import { WEB_AUTOMATION_ACTION_TYPES, type WebAutomationActionType } from "../../actions/types";
import { createWebAutomationOutputNodeDefinition, webAutomationOutputNodeDefinitions, webAutomationOutputNodeId } from "../definitions";
import { webAutomationExtractListIssues } from "../extract-list";

const nodes = webAutomationOutputNodeDefinitions;

function nodeFor(outputId: WebAutomationActionType) {
  const node = nodes.find((definition) => definition.outputAction?.fixedOutputId === outputId);
  assert.ok(node, `${outputId} has no output node`);
  return node;
}

function parameterIds(outputId: WebAutomationActionType): string[] {
  return nodeFor(outputId).parameters.map((parameter) => parameter.id);
}

const WEEK_ONE_ACTIONS: WebAutomationActionType[] = [
  "web.dom.check", "web.dom.assert", "web.dom.extract_list",
  "web.dom.upload", "web.dom.dialog", "web.browser.tab", "web.browser.download"
];

test("every action type has one valid output node, derived from its own schema row", () => {
  assert.equal(nodes.length, WEB_AUTOMATION_ACTION_TYPES.length);
  for (const outputId of WEB_AUTOMATION_ACTION_TYPES) {
    const node = nodeFor(outputId);
    assert.equal(node.id, webAutomationOutputNodeId(outputId));
    const validation = validateAutomationStudioNodeDefinition(node);
    assert.equal(validation.ok, true, `${outputId}: ${validation.issues.map((issue) => issue.code).join(", ")}`);
    const definition = webAutomationActionDefinitions.find((candidate) => candidate.actionType === outputId);
    assert.equal(node.label, definition?.label, `${outputId} label`);
    assert.deepEqual(node.metadata?.parameterSchema, definition?.parameterSchema, `${outputId} carries its own parameter schema`);
    // Every parameter is state-bindable but a record output, which Core
    // requires to be a literal (see the list extraction's own test below).
    const bindable = node.parameters.filter((parameter) => parameter.id !== "recordOutput");
    assert.equal(bindable.every((parameter) => parameter.allowStateBinding === true), true, `${outputId} parameters must be state-bindable`);
    assert.equal(typeof node.icon === "string" && node.icon.length > 0, true, `${outputId} needs an icon`);
  }
});

test("a node's required parameters are exactly the ones its schema requires", () => {
  for (const outputId of WEB_AUTOMATION_ACTION_TYPES) {
    const schema = webAutomationActionDefinitions.find((candidate) => candidate.actionType === outputId)?.parameterSchema;
    const required = Array.isArray(schema?.required) ? schema.required.filter((key): key is string => typeof key === "string") : [];
    for (const key of required) {
      const parameter = nodeFor(outputId).parameters.find((candidate) => candidate.id === key);
      // A required schema key with no node parameter cannot be authored at all.
      assert.ok(parameter, `${outputId} requires ${key} but offers no parameter for it`);
      assert.equal(parameter.required, true, `${outputId}.${key} must be required on the node`);
    }
  }
});

test("each Week 1 action offers the structured parameter its command field expects", () => {
  assert.equal(parameterIds("web.dom.check").includes("checked"), true);
  const checked = nodeFor("web.dom.check").parameters.find((parameter) => parameter.id === "checked");
  assert.equal(checked?.valueType, "boolean");
  assert.equal(checked?.defaultValue, true);
  for (const [outputId, parameterId] of [
    ["web.dom.assert", "assert"],
    ["web.dom.extract_list", "extractList"],
    ["web.dom.upload", "upload"],
    ["web.dom.dialog", "dialog"],
    ["web.browser.tab", "tab"],
    ["web.browser.download", "download"]
  ] as Array<[WebAutomationActionType, string]>) {
    const parameter = nodeFor(outputId).parameters.find((candidate) => candidate.id === parameterId);
    assert.ok(parameter, `${outputId} offers no ${parameterId} parameter`);
    assert.equal(parameter.valueType, "object", `${outputId}.${parameterId} carries the command field's shape`);
  }
});

test("the actions that act on an element can be aimed at one, and the others cannot", () => {
  // A target is the selector plus the fingerprint and visual target replay
  // falls back on, so every element-scoped action offers all of them.
  for (const outputId of ["web.dom.check", "web.dom.assert", "web.dom.upload"] as WebAutomationActionType[]) {
    for (const parameterId of ["target", "selector", "element", "visualTarget"]) {
      assert.equal(parameterIds(outputId).includes(parameterId), true, `${outputId} is missing ${parameterId}`);
    }
  }
  // A dialog, a tab and a download act on the browser, and a list extraction
  // carries its own item selector, so none of them takes an element target.
  for (const outputId of ["web.dom.dialog", "web.browser.tab", "web.browser.download", "web.dom.extract_list"] as WebAutomationActionType[]) {
    assert.equal(parameterIds(outputId).includes("selector"), false, `${outputId} must not take an element target`);
  }
});

test("the original eleven gained the node parameters D6 added", () => {
  assert.equal(parameterIds("web.browser.navigate").includes("newTab"), true);
  assert.equal(parameterIds("web.dom.select").includes("option"), true);
  assert.equal(parameterIds("web.dom.keypress").includes("modifiers"), true);
  assert.equal(parameterIds("web.dom.wait_for_selector").includes("wait"), true);
  assert.equal(parameterIds("web.dom.wait_for_text").includes("wait"), true);
  // `toElement` needs somewhere to scroll to, so scroll gained a target.
  const scroll = parameterIds("web.dom.scroll");
  assert.equal(scroll.includes("scroll"), true);
  assert.equal(scroll.includes("selector"), true);
});

test("no node declares a parameter twice", () => {
  for (const node of nodes) {
    const ids = node.parameters.map((parameter) => parameter.id);
    assert.equal(new Set(ids).size, ids.length, `${node.id} declares a parameter twice`);
  }
});

test("the seven Week 1 actions are all registered", () => {
  for (const outputId of WEEK_ONE_ACTIONS) {
    assert.equal(WEB_AUTOMATION_ACTION_TYPES.includes(outputId), true, `${outputId} is not a registered action type`);
    assert.ok(nodeFor(outputId));
  }
});

// -- What Core reads off a node beyond its parameters -------------------------

test("every node can carry the post-conditions Core's transition comparison evaluates", () => {
  // Core reads `node.parameterValues.expectedState` for any node
  // (`runtime/executor/expected-transition.ts`) and hands it to the host
  // boundary's expectation evaluator. Nothing else in this repository writes
  // that path, so a node that does not declare the parameter can never carry a
  // post-condition and the comparison has nothing to evaluate.
  for (const outputId of WEB_AUTOMATION_ACTION_TYPES) {
    const parameter = nodeFor(outputId).parameters.find((candidate) => candidate.id === "expectedState");
    assert.ok(parameter, `${outputId} offers no expectedState parameter`);
    assert.equal(parameter.valueType, "object", `${outputId}.expectedState carries { conditions, mode, timeoutMs }`);
    assert.equal(parameter.required, undefined, `${outputId}.expectedState is optional: not every action has a post-condition`);
    assert.equal(parameter.defaultValue, undefined, `${outputId}.expectedState has no default: an empty condition list would report a pass`);
  }
});

test("element targeting is declared by exactly the actions that cannot run without an element", () => {
  // `metadata.elementTarget` is what makes Core resolve the recorded
  // fingerprint against runtime candidates and apply its confidence floor
  // (`runtime/io-policy.ts`). Core fails an action outright when the flag is
  // set and the parameters carry no fingerprint, so an action that can run
  // without one — a delta scroll, a key press to the focused element, a URL
  // assertion, a tab operation — must not declare it.
  const declared = WEB_AUTOMATION_ACTION_TYPES.filter((outputId) => nodeFor(outputId).metadata?.elementTarget === true);
  assert.deepEqual(declared.slice().sort(), [
    "web.dom.check",
    "web.dom.clear",
    "web.dom.click",
    "web.dom.extract",
    "web.dom.select",
    "web.dom.type",
    "web.dom.upload",
    "web.dom.wait_for_selector"
  ]);
  // The flag is derived from the action's own schema row, so the two cannot drift.
  for (const outputId of WEB_AUTOMATION_ACTION_TYPES) {
    const schema = webAutomationActionDefinitions.find((candidate) => candidate.actionType === outputId)?.parameterSchema;
    const requiresSelector = Array.isArray(schema?.required) && schema.required.includes("selector");
    assert.equal(nodeFor(outputId).metadata?.elementTarget === true, requiresSelector, `${outputId}: element targeting must follow its schema`);
  }
});

test("the list extraction tells Core where its records are, and no other node claims to return records", () => {
  // Core's record capture reads `outputs.result` at `recordsPath`
  // (`runtime/executor/record-capture.ts`), and its proposal lift defaults that
  // path from the output's `metadata.recordsPath` (Core CD19), rejecting a
  // candidate with none. Core never hard-codes `extracted`, so without this key
  // a recorded list extraction cannot become a node that saves its records.
  //
  // Two segments, and the second is this domain's word. The dispatch answers
  // `{ status, message, result }` with the client's action result under
  // `result` (`io/gateway-output-dispatcher.ts`, carried through by
  // `runtime/adapter.ts`), and Core puts that whole object at `outputs.result`.
  // A one-segment path read `outputs.result.extracted`, which is never an
  // array, and the first recorded extraction to reach the capture failed at
  // `record_output.records_missing` having saved nothing.
  assert.equal(nodeFor("web.dom.extract_list").metadata?.recordsPath, "result.extracted");
  // `web.dom.extract` answers on `extracted` too, but with one value rather than
  // a list, so a default path there could never capture anything.
  const declared = WEB_AUTOMATION_ACTION_TYPES.filter((outputId) => nodeFor(outputId).metadata?.recordsPath !== undefined);
  assert.deepEqual(declared, ["web.dom.extract_list"]);
});

test("exactly the verbs that prove the page's state tell Core their success verifies a change", () => {
  // Core's change verdict counts a later node as a downstream assertion only
  // when its definition's `metadata.verifiesState` is exactly `true` (Core
  // `AUTOMATION_STUDIO_NODE_VERIFIES_STATE_METADATA_KEY`). The key is spelled
  // out here rather than read from the domain, so a misspelt constant fails.
  const declared = WEB_AUTOMATION_ACTION_TYPES.filter((outputId) => nodeFor(outputId).metadata?.verifiesState === true);
  assert.deepEqual(declared.slice().sort(), ["web.dom.assert", "web.dom.wait_for_selector", "web.dom.wait_for_text"]);
  for (const outputId of declared) {
    const validation = validateAutomationStudioNodeDefinition(nodeFor(outputId));
    assert.equal(validation.ok, true, `${outputId}: ${validation.issues.map((issue) => issue.code).join(", ")}`);
  }
  // Every other node leaves the key out entirely: an action succeeding, or a
  // read returning whatever it found, proves nothing about the page, and a
  // stray `false` or `"true"` would be one edit away from counting.
  for (const outputId of WEB_AUTOMATION_ACTION_TYPES.filter((candidate) => !declared.includes(candidate))) {
    assert.equal(Object.hasOwn(nodeFor(outputId).metadata ?? {}, "verifiesState"), false, `${outputId} must not declare verifiesState`);
  }
});

test("the list extraction offers a timeout, because a paginated read outlasts Core's default (D14)", () => {
  // The request carries no timeout of its own: the command's `timeoutMs` is the
  // one the page honours, and this parameter is where a node states it.
  const parameter = nodeFor("web.dom.extract_list").parameters.find((candidate) => candidate.id === "timeoutMs");
  assert.ok(parameter, "web.dom.extract_list offers no timeoutMs parameter");
  assert.equal(parameter.valueType, "number");
  assert.equal(parameter.defaultValue, 10_000, "the same default as every element-scoped action");
  assert.equal(parameter.required, undefined, "a timeout is optional");
  assert.equal(parameter.allowStateBinding, true);
});

// -- A list extraction a model builds from an instruction ---------------------

test("the list extraction can save a dataset, declared as Core's policy action declares it", () => {
  const node = nodeFor("web.dom.extract_list");
  const parameter = node.parameters.find((candidate) => candidate.id === "recordOutput");
  assert.ok(parameter, "web.dom.extract_list offers no recordOutput parameter");
  assert.equal(parameter.valueType, "json");
  assert.equal(parameter.defaultValue, null);
  assert.equal(parameter.ui?.control, "record-output");
  // A binding could replace the schema, and with it the excluded fields, at run time.
  assert.equal(parameter.allowStateBinding, false);
  assert.equal(parameter.required, undefined, "left empty, the node derives one");
  // No other node offers one: only the list extraction returns records.
  const offering = WEB_AUTOMATION_ACTION_TYPES.filter((outputId) => parameterIds(outputId).includes("recordOutput"));
  assert.deepEqual(offering, ["web.dom.extract_list"]);
});

test("the nodes that return records declare a records port for a later node to read", () => {
  const records = nodeFor("web.dom.extract_list").outputs.find((port) => port.id === "records");
  assert.deepEqual(records, { id: "records", label: "Records", valueType: "array", role: "data" });
  for (const outputId of WEB_AUTOMATION_ACTION_TYPES) {
    const node = nodeFor(outputId);
    assert.equal(node.outputs.some((port) => port.id === "records"), node.metadata?.recordsPath !== undefined, `${outputId}: a records port follows a records path`);
    assert.deepEqual(node.outputs.slice(0, 2).map((port) => port.id), ["success", "failed"]);
  }
});

test("the list extraction carries the words of a scraping request, and no other node does", () => {
  const tags = nodeFor("web.dom.extract_list").tags ?? [];
  for (const tag of ["web-automation", "output", "scrape", "collect", "extract", "list", "table", "rows", "every page", "next page", "load more"]) {
    assert.equal(tags.includes(tag), true, `web.dom.extract_list is missing tag ${tag}`);
  }
  for (const outputId of WEB_AUTOMATION_ACTION_TYPES.filter((candidate) => candidate !== "web.dom.extract_list")) {
    assert.deepEqual(nodeFor(outputId).tags, ["web-automation", "output"], `${outputId} tags`);
  }
});

test("the list extraction describes its request for a model to write one", () => {
  const node = nodeFor("web.dom.extract_list");
  // Core's catalog keeps 240 characters of a node description, and cut it at
  // 80 before, so the first sentence says what the node is for on its own.
  assert.equal(node.description.length <= 240, true, `${node.description.length} characters`);
  const firstSentence = node.description.slice(0, node.description.indexOf(".") + 1);
  assert.equal(firstSentence.length > 0 && firstSentence.length <= 80, true, firstSentence);
  assert.match(firstSentence, /scrape/iu);
  // The grammar goes with the parameter, whose description Core keeps to 600.
  const extractList = node.parameters.find((candidate) => candidate.id === "extractList");
  const grammar = extractList?.description ?? "";
  assert.equal(grammar.length <= 600, true, `${grammar.length} characters`);
  for (const term of ["item", "fields", "css@attr", "column:", "paginate", "minItems", "maxItems", ...WEB_AUTOMATION_EXTRACT_PAGINATION_MODES, ...WEB_AUTOMATION_EXTRACT_FIELD_KINDS]) {
    assert.equal(grammar.includes(term), true, `the extractList description does not mention ${term}`);
  }
  assert.equal(grammar.includes(String(WEB_AUTOMATION_EXTRACT_MAX_PAGES)), true);
  assert.equal(grammar.includes(String(WEB_AUTOMATION_EXTRACT_MAX_ITEMS)), true);
  // Its example is a request the page would run, and one with no issues.
  assert.notEqual(webAutomationExtractListRequestValue(extractList?.example), undefined);
  assert.deepEqual(webAutomationExtractListIssues(extractList?.example), []);
  // Every definition gets its own copy, so no caller can change another's.
  const again = createWebAutomationOutputNodeDefinition(webAutomationActionDefinitions.find((candidate) => candidate.actionType === "web.dom.extract_list")!);
  assert.notEqual(again.parameters.find((candidate) => candidate.id === "extractList")?.example, extractList?.example);
  // Every other node keeps its action's own description.
  for (const outputId of WEB_AUTOMATION_ACTION_TYPES.filter((candidate) => candidate !== "web.dom.extract_list")) {
    const definition = webAutomationActionDefinitions.find((candidate) => candidate.actionType === outputId);
    assert.equal(nodeFor(outputId).description, definition?.description, `${outputId} description`);
  }
});
