import type { ScenarioWorkflow } from "@fluxiq-web-extension/test-contracts";
import { companyReviewExpected } from "./expected.js";

export const companyReviewWorkflow: ScenarioWorkflow = {
  id: "review-service-without-booking",
  description: "review service without booking",
  recordingScript: [{"id":"review-chat","operation":"waitForState","target":"div[title=\"Close\"]","timeoutMs":6000},{"id":"review-chat-close","operation":"click","target":"div[title=\"Close\"]"},{"id":"review-consent","operation":"click","target":"button:text-is(\"Accept all\")"},{"id":"review-newsletter","operation":"waitForState","target":"[aria-label=\"Newsletter\"]","timeoutMs":15000},{"id":"review-newsletter-no","operation":"click","target":"span:text-is(\"No thanks, I will pay full price\")"},{"id":"review-open","operation":"click","target":"nav a:text-is(\"Book a service\")"},{"id":"review-branch","operation":"click","target":"frame:Slotwise booking/div:has(> strong:text-is(\"Hollins Cross\"))"},{"id":"review-branch-next","operation":"click","target":"frame:Slotwise booking/button:text-is(\"Next\")"},{"id":"review-service","operation":"click","target":"frame:Slotwise booking/div:text-is(\"Combi boiler · £95.00\")"},{"id":"review-service-next","operation":"click","target":"frame:Slotwise booking/button:text-is(\"Next\")"},{"id":"review-later","operation":"click","target":"frame:Slotwise booking/div:text-is(\"Later ›\")"},{"id":"review-slot","operation":"click","target":"frame:Slotwise booking/div:has(> div:text-is(\"Mon 05/10\")) > div:text-is(\"10:30\")"},{"id":"review-slot-next","operation":"click","target":"frame:Slotwise booking/button:text-is(\"Next\")"},{"id":"review-fullName","operation":"type","target":"frame:Slotwise booking/input[name=\"fullName\"]","value":"Ada Synthetic"},{"id":"review-email","operation":"type","target":"frame:Slotwise booking/input[name=\"email\"]","value":"ada.synthetic@example.test"},{"id":"review-phone","operation":"type","target":"frame:Slotwise booking/input[name=\"phone\"]","value":"07700 900123"},{"id":"review-postcode","operation":"type","target":"frame:Slotwise booking/input[name=\"postcode\"]","value":"KL6 2RN"},{"id":"review-details-next","operation":"click","target":"frame:Slotwise booking/button:text-is(\"Next\")"},{"id":"review-ready","operation":"waitForState","target":"frame:Slotwise booking/h2:text-is(\"Check and pay your deposit\")","timeoutMs":5000},{"id":"extract-service-review","operation":"extract","target":"frame:Slotwise booking/div:has(> div:text-is(\"Branch\")):has(> div:text-is(\"Deposit today\"))","fields":{"branch":"div:nth-child(2) strong","service":"div:nth-child(4) strong","date":"div:nth-child(6) strong","time":"div:nth-child(8) strong","engineer":"div:nth-child(10) strong","price":"div:nth-child(12) strong","deposit":"div:nth-child(14) strong"}}],
  expected: companyReviewExpected,
};
