import type { AuthoredListing } from "../listing.js";

/**
 * Bicycles, and the things a search for "bike" also finds. Twelve of them are
 * the extraction task's answer; the rest are each a reason a careless reading
 * picks the wrong ones: the same mountain bike relisted further away by a
 * reseller, a reduced price that is still over the limit, a sold bike, a tired
 * one, one a mile past the radius, and a folding bike nine days old.
 */
export const BICYCLE_LISTINGS: readonly AuthoredListing[] = [
  { key: "ridgeline-mtb-upper", title: "Ridgeline 27.5in mountain bike, medium frame", category: "bicycles", price: 240, was: 300, condition: "good", place: "upper-kelford", hours: 30, seller: "jordan-pike", delivery: "pickup",
    description: "Hardtail, 1x10 gears, lockout forks. New chain and brake pads in the spring. A few scuffs on the top tube, nothing structural. Collection only, can meet at the Upper Kelford Co-op car park.", details: [["Brand", "Ridgeline"], ["Frame size", "Medium (17in)"], ["Colour", "Slate blue"]] },
  { key: "ridgeline-mtb-hallam", title: "Ridgeline 27.5in mountain bike, medium frame", category: "bicycles", price: 180, condition: "good", place: "hallam-cross", hours: 50, seller: "ridgeline-deals", delivery: "both",
    description: "Great condition!!! Fast sale. Message for more pics. Can deliver anywhere for a small fee.", details: [["Brand", "Ridgeline"], ["Colour", "Slate blue"]] },
  { key: "folding-16in", title: "Folding bike, 16in wheels, 6-speed, barely used", category: "bicycles", price: 165, condition: "like-new", place: "upper-kelford", hours: 44, seller: "morgan-tate", delivery: "pickup",
    description: "Bought for the train commute and then started working from home. Ridden maybe ten times. Folds in about twenty seconds, comes with the front carrier bag and the original allen keys. Always kept indoors.", details: [["Wheel size", "16in"], ["Gears", "6-speed"], ["Colour", "Racing green"]] },
  { key: "folding-commuter", title: "Folding commuter bike with rack", category: "bicycles", price: 120, condition: "good", place: "kelford-harbour", hours: 20, seller: "leila-farah", delivery: "pickup",
    description: "20in wheels, 7 gears, rear rack and mudguards. Some rust on the chainring bolts. Rides well.", details: [["Wheel size", "20in"], ["Gears", "7-speed"]] },
  { key: "folding-20in-brackwater", title: "Folding bike, 20in, alloy frame", category: "bicycles", price: 95, condition: "like-new", place: "brackwater", hours: 216, seller: "fergus-lyle", delivery: "pickup",
    description: "Lightweight alloy folder, used twice. Clearing the garage.", details: [["Wheel size", "20in"]] },
  { key: "folding-pellingford", title: "Folding bike, 20in, like new, with mudguards", category: "bicycles", price: 150, condition: "like-new", place: "pellingford", hours: 26, seller: "imogen-blake", delivery: "both",
    description: "As new. Mudguards and a kickstand fitted. Happy to post at the buyer's cost.", details: [["Wheel size", "20in"]] },
  { key: "folding-sold", title: "Folding bike, 16in, 3-speed", category: "bicycles", price: 130, condition: "like-new", place: "kelford-centre", hours: 60, seller: "owen-bracegirdle", delivery: "pickup", sold: true,
    description: "Three-speed hub, very light. Sold, thanks all.", details: [["Wheel size", "16in"], ["Gears", "3-speed"]] },
  { key: "road-56", title: "Road bike, 56cm aluminium frame, 16-speed", category: "bicycles", price: 285, condition: "good", place: "kelford-centre", hours: 100, seller: "tomasz-wrona", delivery: "pickup",
    description: "Serviced last month: new cables, bar tape and tyres. Would suit someone 5ft 9 to 6ft. Pedals not included.", details: [["Frame size", "56cm"], ["Gears", "2x8"]] },
  { key: "vintage-road", title: "Vintage steel road bike, 58cm, recently serviced", category: "bicycles", price: 210, condition: "fair", place: "saltmarsh-row", hours: 75, seller: "niamh-doherty", delivery: "pickup",
    description: "1980s steel frame, downtube shifters. Paint is tired and there is surface rust on the rear dropouts, but it has had new bearings and brake blocks." },
  { key: "hybrid-womens", title: "Hybrid bike, women's 17in frame, 21 gears", category: "bicycles", price: 135, condition: "good", place: "brackwater", hours: 140, seller: "beatrix-fell", delivery: "pickup",
    description: "Step-through frame, comfortable saddle, bell and lights included.", details: [["Frame size", "17in"], ["Gears", "21-speed"]] },
  { key: "kids-mtb-24", title: "Kids' mountain bike, 24in wheels", category: "bicycles", price: 100, condition: "good", place: "ashby-moor", hours: 12, seller: "kwame-asante", delivery: "pickup",
    description: "Outgrown. Suits roughly 8 to 12 years. Front suspension, 18 gears, recently had the brakes adjusted.", details: [["Wheel size", "24in"]] },
  { key: "balance-bike", title: "Kids' balance bike, 12in", category: "bicycles", price: 35, condition: "like-new", place: "kelford-harbour", hours: 8, seller: "casey-moreno", delivery: "pickup",
    description: "Wooden balance bike, adjustable seat." },
  { key: "ebike", title: "Electric bike, 250W, 40-mile range", category: "bicycles", price: 400, condition: "like-new", place: "saltmarsh-row", hours: 170, seller: "harper-quinlan", delivery: "pickup",
    description: "Rear hub motor, removable battery with charger. Under 200 miles on it. Moving abroad so it has to go.", details: [["Motor", "250W"], ["Range", "Up to 40 miles"]] },
  { key: "e-folding", title: "Electric folding bike, 20in", category: "bicycles", price: 420, was: 480, condition: "like-new", place: "kelford-harbour", hours: 96, seller: "dana-whitlock", delivery: "both",
    description: "Folding e-bike, 36V battery, three assist levels. Comes with the charger and a folding lock.", details: [["Wheel size", "20in"]] },
  { key: "gravel-54", title: "Gravel bike, 54cm, carbon fork, 2x10", category: "bicycles", price: 395, condition: "like-new", place: "hallam-cross", hours: 30, seller: "ellis-carver", delivery: "pickup",
    description: "Barely ridden gravel bike, tubeless-ready wheels.", details: [["Frame size", "54cm"]] },
  { key: "gravel-52", title: "Gravel bike, 52cm, hydraulic disc brakes", category: "bicycles", price: 375, condition: "good", place: "upper-kelford", hours: 220, seller: "priya-nandakumar", delivery: "pickup",
    description: "Hydraulic discs, 700x40 tyres, bottle cages. Selling because I have gone back to running.", details: [["Frame size", "52cm"]] },
  { key: "bmx", title: "BMX, 20in, pegs included", category: "bicycles", price: 90, condition: "good", place: "kelford-centre", hours: 15, seller: "casey-moreno", delivery: "pickup",
    description: "Four pegs, gyro brake. Some scratches." },
  { key: "cruiser", title: "Cruiser bike with basket, mint green", category: "bicycles", price: 150, condition: "new", place: "kelford-harbour", hours: 5, seller: "harper-quinlan", delivery: "pickup",
    description: "Unwanted gift, never ridden, still has the tags on. Wicker basket and bell.", details: [["Colour", "Mint green"]] },
  { key: "tandem", title: "Tandem bicycle, recently serviced", category: "bicycles", price: 350, condition: "fair", place: "brackwater", hours: 300, seller: "rosa-lindqvist", delivery: "pickup",
    description: "Heavy old tandem. Serviced, but the paintwork is rough." },
  { key: "fs-29er", title: "Mountain bike, full suspension, 29er, large", category: "bicycles", price: 650, was: 800, condition: "good", place: "upper-kelford", hours: 90, seller: "jordan-pike", delivery: "pickup",
    description: "Full suspension trail bike, dropper post, recently serviced shock.", details: [["Frame size", "Large"]] },
  { key: "hardtail-26", title: "Mountain bike, hardtail, 26in, small frame", category: "bicycles", price: 110, condition: "good", place: "wendle-green", hours: 40, seller: "gideon-marsh", delivery: "pickup",
    description: "Small frame, would suit a teenager." },
  { key: "single-speed", title: "Single-speed town bike, 54cm", category: "bicycles", price: 190, condition: "like-new", place: "kelford-centre", hours: 62, seller: "tomasz-wrona", delivery: "pickup",
    description: "Flip-flop hub, riser bars, cork grips. Ridden a handful of times.", details: [["Frame size", "54cm"]] },
  { key: "hybrid-mens", title: "Hybrid bike, men's 21in frame", category: "bicycles", price: 160, condition: "fair", place: "ashby-moor", hours: 33, seller: "fergus-lyle", delivery: "pickup",
    description: "Needs a new chain and the rear derailleur adjusting." },
  { key: "road-50", title: "Road bike, 50cm, triple chainset", category: "bicycles", price: 230, condition: "good", place: "ashby-moor", hours: 400, seller: "niamh-doherty", delivery: "pickup",
    description: "Triple chainset, good for hills. Small frame.", details: [["Frame size", "50cm"]] },
  { key: "kids-16", title: "Kids' bike, 16in, with stabilisers", category: "bicycles", price: 45, condition: "good", place: "saltmarsh-row", hours: 18, seller: "kwame-asante", delivery: "pickup",
    description: "Stabilisers included, suits 4 to 6 years." },
  { key: "cargo", title: "Cargo bike, box front, seats two children", category: "bicycles", price: 1250, condition: "like-new", place: "kelford-centre", hours: 500, seller: "rosa-lindqvist", delivery: "pickup",
    description: "Box cargo bike with rain cover and two harnesses. Collection only." },
  { key: "old-kids", title: "Old kids' bike, needs new tyres", category: "bicycles", price: 0, condition: "fair", place: "upper-kelford", hours: 3, seller: "gideon-marsh", delivery: "pickup",
    description: "Free to whoever collects. Needs tyres and a bit of love." },
  { key: "carbon-road", title: "Carbon road bike, 58cm, 22-speed", category: "bicycles", price: 395, was: 450, condition: "like-new", place: "kelford-harbour", hours: 120, seller: "ellis-carver", delivery: "pickup",
    description: "Full carbon frame and fork, 2x11. Upgraded to a bigger frame so this has to go.", details: [["Frame size", "58cm"], ["Gears", "2x11"]] },
  { key: "road-54-sold", title: "Road bike, 54cm, 18-speed, new tyres", category: "bicycles", price: 199, condition: "good", place: "kelford-harbour", hours: 80, seller: "imogen-blake", delivery: "pickup", sold: true,
    description: "Sold pending collection." },
  { key: "hybrid-castle", title: "Hybrid bike, 19in frame, pannier rack", category: "bicycles", price: 145, condition: "good", place: "castle-dunmore", hours: 55, seller: "owen-bracegirdle", delivery: "pickup",
    description: "Pannier rack and mudguards, good tyres." },
  { key: "road-52-alex", title: "Road bike, 52cm, 18-speed", category: "bicycles", price: 220, condition: "good", place: "pellingford", hours: 260, seller: "alex-rowe", delivery: "pickup",
    description: "Lovely light road bike. Open to offers." },
  { key: "exercise-bike", title: "Exercise bike, magnetic resistance", category: "sport", price: 85, condition: "good", place: "kelford-centre", hours: 22, seller: "dana-whitlock", delivery: "pickup",
    description: "Eight resistance levels, heart-rate grips. Folds flat." },
  { key: "bike-helmet", title: "Bike helmet, adult M, 55-59cm", category: "sport", price: 20, condition: "like-new", place: "kelford-harbour", hours: 14, seller: "leila-farah", delivery: "both",
    description: "Worn a couple of times, no knocks." },
  { key: "bike-rack", title: "Bike rack for car, carries 3 bikes", category: "sport", price: 45, condition: "good", place: "upper-kelford", hours: 66, seller: "priya-nandakumar", delivery: "pickup",
    description: "Boot-mounted rack with straps." },
];
