import type { AuthoredListing } from "../listing.js";

/**
 * Everything else a local marketplace carries, so the home feed and every
 * category in the sidebar read like a real one. The desk lamp is the other
 * listing the account had saved before the session began; the floor lamp is
 * one of the two conversations it already had going.
 */
export const HOUSEHOLD_LISTINGS: readonly AuthoredListing[] = [
  { key: "desk-lamp", title: "Adjustable desk lamp, black", category: "home-goods", price: 22, condition: "like-new", place: "kelford-centre", hours: 300, seller: "sam-ellery", delivery: "both",
    description: "Spring-balanced arm, E27 fitting. Bulb included." },
  { key: "floor-lamp", title: "Floor lamp, brass effect", category: "home-goods", price: 30, condition: "good", place: "saltmarsh-row", hours: 180, seller: "sam-ellery", delivery: "pickup",
    description: "Tall floor lamp with a brass-effect finish." },
  { key: "table-lamp", title: "Table lamp with linen shade", category: "home-goods", price: 15, condition: "good", place: "kelford-harbour", hours: 25, seller: "rosa-lindqvist", delivery: "both",
    description: "Ceramic base, linen shade." },
  { key: "curtains", title: "Pair of blackout curtains, 168x183cm", category: "home-goods", price: 18, condition: "like-new", place: "brackwater", hours: 40, seller: "beatrix-fell", delivery: "both",
    description: "Charcoal grey, eyelet top." },
  { key: "casserole", title: "Cast iron casserole dish, 24cm", category: "home-goods", price: 25, condition: "good", place: "upper-kelford", hours: 60, seller: "harper-quinlan", delivery: "pickup",
    description: "Enamelled cast iron, a chip on the lid rim." },
  { key: "mirror", title: "Standing mirror, full length", category: "home-goods", price: 40, condition: "good", place: "kelford-centre", hours: 16, seller: "casey-moreno", delivery: "pickup",
    description: "Full-length mirror on a wooden stand." },
  { key: "phone", title: "Smartphone, 128GB, unlocked, cracked back", category: "electronics", price: 90, condition: "fair", place: "kelford-harbour", hours: 9, seller: "gideon-marsh", delivery: "both",
    description: "Screen perfect, back glass cracked. Unlocked to all networks." },
  { key: "headphones", title: "Wireless headphones, noise cancelling", category: "electronics", price: 60, condition: "like-new", place: "upper-kelford", hours: 35, seller: "ellis-carver", delivery: "both",
    description: "Boxed with the case and cable." },
  { key: "monitor", title: "27in monitor, 1440p", category: "electronics", price: 120, condition: "good", place: "saltmarsh-row", hours: 52, seller: "tomasz-wrona", delivery: "pickup",
    description: "No dead pixels, stand included." },
  { key: "console", title: "Games console with two controllers", category: "electronics", price: 180, condition: "good", place: "kelford-centre", hours: 27, seller: "kwame-asante", delivery: "pickup",
    description: "Two controllers and the charging dock." },
  { key: "laptop", title: "Laptop, 14in, 16GB RAM", category: "electronics", price: 320, condition: "good", place: "ashby-moor", hours: 72, seller: "dana-whitlock", delivery: "pickup",
    description: "Battery holds about five hours. Freshly reset." },
  { key: "guitar", title: "Acoustic guitar with gig bag", category: "instruments", price: 85, condition: "good", place: "kelford-harbour", hours: 44, seller: "niamh-doherty", delivery: "pickup",
    description: "Full-size dreadnought, new strings." },
  { key: "digital-piano", title: "Digital piano, 88 weighted keys", category: "instruments", price: 280, condition: "like-new", place: "brackwater", hours: 110, seller: "jordan-pike", delivery: "pickup",
    description: "With stand and sustain pedal." },
  { key: "violin", title: "Violin, 3/4 size, for a child", category: "instruments", price: 70, condition: "good", place: "upper-kelford", hours: 88, seller: "priya-nandakumar", delivery: "both",
    description: "Case, bow and rosin included." },
  { key: "train-set", title: "Wooden train set, 60 pieces", category: "toys", price: 25, condition: "good", place: "kelford-centre", hours: 19, seller: "leila-farah", delivery: "pickup",
    description: "Track, bridges and six trains." },
  { key: "board-games", title: "Board game bundle, 6 games", category: "toys", price: 20, condition: "good", place: "saltmarsh-row", hours: 31, seller: "fergus-lyle", delivery: "pickup",
    description: "All complete, counted." },
  { key: "kids-scooter", title: "Kids' scooter, light-up wheels", category: "toys", price: 15, condition: "like-new", place: "kelford-harbour", hours: 11, seller: "casey-moreno", delivery: "pickup",
    description: "Three-wheel scooter, suits 3 to 6." },
  { key: "lawnmower", title: "Petrol lawnmower, self-propelled", category: "garden", price: 120, condition: "good", place: "ashby-moor", hours: 58, seller: "owen-bracegirdle", delivery: "pickup",
    description: "Starts first pull, serviced in March." },
  { key: "garden-bench", title: "Garden bench, teak", category: "garden", price: 90, condition: "fair", place: "brackwater", hours: 130, seller: "rosa-lindqvist", delivery: "pickup",
    description: "Weathered teak, sturdy." },
  { key: "planters", title: "Four raised bed planters", category: "garden", price: 0, condition: "fair", place: "upper-kelford", hours: 7, seller: "gideon-marsh", delivery: "pickup",
    description: "Free, must collect this weekend." },
  { key: "hatchback", title: "2012 hatchback, 1.2 petrol, 78,000 miles", category: "vehicles", price: 2950, condition: "good", place: "kelford-centre", hours: 46, seller: "harper-quinlan", delivery: "pickup",
    description: "Full service history, MOT until June." },
  { key: "moped", title: "Scooter, 125cc, 2019", category: "vehicles", price: 1650, condition: "good", place: "hallam-cross", hours: 77, seller: "ellis-carver", delivery: "pickup",
    description: "Low mileage, top box included." },
  { key: "hiking-jacket", title: "Waterproof hiking jacket, men's M", category: "apparel", price: 35, condition: "like-new", place: "kelford-harbour", hours: 13, seller: "beatrix-fell", delivery: "both",
    description: "Worn once, fully taped seams." },
  { key: "leather-boots", title: "Leather boots, size 6", category: "apparel", price: 40, condition: "good", place: "upper-kelford", hours: 29, seller: "imogen-blake", delivery: "both",
    description: "Brown leather, resoled last year." },
  { key: "yoga-set", title: "Yoga mat and blocks", category: "sport", price: 12, condition: "good", place: "kelford-centre", hours: 21, seller: "leila-farah", delivery: "pickup",
    description: "Mat, two blocks and a strap." },
  { key: "kettlebells", title: "Kettlebell set, 4-16kg", category: "sport", price: 55, condition: "good", place: "saltmarsh-row", hours: 64, seller: "kwame-asante", delivery: "pickup",
    description: "Four kettlebells: 4, 8, 12 and 16kg." },
];
