import type { ClassRole } from "./classes.js";

/**
 * The emitted stylesheet. The first rules undo the lab's shared page shell,
 * which is centred and 48rem wide; a marketplace is neither. The geometry that
 * matters to a run is deliberate: the listing page's action bar is pinned to
 * the bottom of a fixed-width right panel, and the chat window is pinned to the
 * bottom-right of the viewport, so an open chat covers Make offer at any
 * window size; and the honeypot is off-screen rather than hidden, so it is
 * still an ordinary field to anything that fills every field it finds.
 */
export function classifiedsStylesheet(k: Record<ClassRole, string>): string {
  const s = (role: ClassRole) => `.${k[role]}`;
  return [
    `body { margin: 0; max-width: none; padding: 0; font: 15px/1.34 "Segoe UI", Helvetica, Arial, sans-serif; color: #050505; background: #f0f2f5; }`,
    `li { display: list-item; gap: 0; margin: 0; }`,
    `nav { display: flex; gap: 0; }`,
    `label { display: inline; margin: 0; }`,
    `button, input, select, textarea { font: inherit; }`,
    `a { color: inherit; text-decoration: none; }`,
    `[hidden] { display: none !important; }`,
    `${s("srOnly")} { position: absolute; width: 1px; height: 1px; overflow: hidden; clip: rect(0 0 0 0); white-space: nowrap; }`,
    `${s("topbar")} { position: sticky; top: 0; z-index: 40; display: flex; align-items: center; gap: 8px; height: 56px; padding: 0 16px; background: #fff; box-shadow: 0 1px 2px rgba(0,0,0,.12); }`,
    `${s("brand")} { display: flex; align-items: center; }`,
    `${s("brandMark")} { padding: 4px 10px; border-radius: 18px; background: #0866ff; color: #fff; font-weight: 700; letter-spacing: -.02em; }`,
    `${s("topSearch")} { width: 240px; }`,
    `${s("topSearchInput")}, ${s("sideSearchInput")} { width: 100%; box-sizing: border-box; padding: 8px 14px; border: 0; border-radius: 20px; background: #f0f2f5; }`,
    `${s("topNav")} { flex: 1; justify-content: center; gap: 8px; }`,
    `${s("topNavItem")} { padding: 14px 34px; border-bottom: 3px solid transparent; color: #65676b; }`,
    `${s("topNavCurrent")} { border-bottom-color: #0866ff; color: #0866ff; }`,
    `${s("topActions")} { display: flex; gap: 8px; }`,
    `${s("iconButton")} { position: relative; display: grid; place-items: center; width: 40px; height: 40px; border-radius: 50%; background: #e4e6eb; cursor: pointer; }`,
    `${s("iconBadge")} { position: absolute; top: -4px; right: -4px; min-width: 18px; padding: 0 4px; border-radius: 9px; background: #e41e3f; color: #fff; font-size: 12px; text-align: center; }`,
    `${s("avatar")} { display: grid; place-items: center; flex: none; width: 36px; height: 36px; border-radius: 50%; background: #c9ccd1; color: #1c1e21; font-size: 13px; font-weight: 600; }`,
    `${s("layout")} { display: grid; grid-template-columns: 300px minmax(0, 1fr); align-items: start; }`,
    `${s("sidebar")} { position: sticky; top: 56px; height: calc(100vh - 56px); overflow: auto; box-sizing: border-box; padding: 12px 12px 40px; background: #fff; box-shadow: 1px 0 2px rgba(0,0,0,.08); }`,
    `${s("sideTitle")} { margin: 4px 8px 10px; font-size: 24px; }`,
    `${s("sideSearch")} { margin: 0 8px 10px; }`,
    `${s("navList")}, ${s("categoryList")} { list-style: none; margin: 0; padding: 0; }`,
    `${s("navItem")}, ${s("categoryLink")} { display: flex; align-items: center; gap: 10px; padding: 9px 8px; border-radius: 8px; font-weight: 500; }`,
    `${s("navCurrent")} { background: #f0f2f5; }`,
    `${s("navBadge")} { margin-left: auto; padding: 0 7px; border-radius: 10px; background: #e7f3ff; color: #0866ff; font-size: 13px; }`,
    `${s("createButton")} { margin: 10px 8px; padding: 8px; border-radius: 6px; background: #e7f3ff; color: #0866ff; font-weight: 600; text-align: center; cursor: pointer; }`,
    `${s("sideSection")} { margin-top: 8px; padding-top: 8px; border-top: 1px solid #ced0d4; }`,
    `${s("sideHeading")} { margin: 8px; font-size: 17px; }`,
    `${s("main")} { min-width: 0; padding: 16px 20px 80px; }`,
    `${s("resultsHead")} { display: flex; align-items: baseline; gap: 12px; margin: 4px 0 14px; }`,
    `${s("resultsTitle")} { margin: 0; font-size: 20px; }`,
    `${s("resultsCount")} { color: #65676b; font-size: 14px; }`,
    `${s("filterBlock")} { margin: 6px 8px 12px; }`,
    `${s("filterLabel")} { display: block; margin-bottom: 6px; font-weight: 600; }`,
    `${s("filterToggle")} { display: flex; justify-content: space-between; padding: 8px 0; font-weight: 600; cursor: pointer; }`,
    `${s("filterPanel")} { padding: 2px 0 6px; }`,
    `${s("priceRow")} { display: flex; align-items: center; gap: 8px; }`,
    `${s("priceInput")} { width: 90px; padding: 8px 10px; border: 1px solid #ced0d4; border-radius: 6px; }`,
    `${s("choiceRow")} { display: flex; align-items: center; gap: 8px; padding: 5px 0; }`,
    `${s("combobox")} { position: relative; padding: 9px 12px; border: 1px solid #ced0d4; border-radius: 6px; background: #fff; cursor: pointer; }`,
    `${s("listbox")} { position: absolute; z-index: 30; left: 0; right: 0; top: 100%; margin-top: 4px; padding: 6px; border-radius: 8px; background: #fff; box-shadow: 0 12px 28px rgba(0,0,0,.2); }`,
    `${s("option")} { padding: 8px; border-radius: 6px; cursor: pointer; }`,
    `${s("option")}[aria-selected="true"] { background: #e7f3ff; }`,
    `${s("feed")} { position: relative; min-height: 300px; }`,
    `${s("grid")} { display: grid; grid-template-columns: repeat(auto-fill, minmax(190px, 1fr)); gap: 18px 10px; }`,
    `${s("list")} { display: grid; gap: 10px; }`,
    `${s("card")} { display: block; }`,
    `${s("cardMedia")} { aspect-ratio: 1; overflow: hidden; border-radius: 8px; background: #e4e6eb; }`,
    `${s("cardImage")}, ${s("pdpPhoto")}, ${s("savedMedia")} img, ${s("rowMedia")} img { display: block; width: 100%; height: 100%; object-fit: cover; }`,
    `${s("cardSponsor")} { margin-bottom: 4px; color: #65676b; font-size: 12px; }`,
    `${s("cardPriceRow")} { margin-top: 6px; }`,
    `${s("cardPrice")} { font-weight: 700; }`,
    `${s("cardWas")}, ${s("pdpWas")} { margin-left: 6px; color: #65676b; text-decoration: line-through; font-size: 13px; }`,
    `${s("cardTitle")} { display: -webkit-box; overflow: hidden; -webkit-line-clamp: 2; -webkit-box-orient: vertical; }`,
    `${s("cardPlace")} { color: #65676b; font-size: 13px; }`,
    `${s("rowCard")} { display: grid; grid-template-columns: 120px 1fr; gap: 12px; padding: 10px; border-radius: 8px; background: #fff; }`,
    `${s("rowMedia")} { width: 120px; height: 120px; overflow: hidden; border-radius: 6px; }`,
    `${s("rowTitle")} { font-weight: 600; }`,
    `${s("rowMeta")} { color: #65676b; font-size: 13px; }`,
    `${s("skeleton")} { height: 260px; border-radius: 8px; background: linear-gradient(90deg, #e4e6eb, #f0f2f5, #e4e6eb); }`,
    `${s("loadMore")} { display: grid; grid-template-columns: repeat(auto-fill, minmax(190px, 1fr)); gap: 10px; min-height: 40px; margin-top: 18px; }`,
    `${s("retry")} { padding: 18px; color: #65676b; text-align: center; }`,
    `${s("linkButton")} { display: inline-block; margin-left: 6px; color: #0866ff; font-weight: 600; cursor: pointer; }`,
    `${s("feedEnd")} { padding: 12px 0; color: #65676b; text-align: center; }`,
    `${s("outsideHead")} { margin: 28px 0 4px; font-size: 17px; }`,
    `${s("challenge")} { position: absolute; inset: 0; z-index: 20; display: grid; place-content: center; gap: 8px; padding: 40px; background: rgba(240,242,245,.96); text-align: center; }`,
    `${s("spinner")} { width: 28px; height: 28px; margin: 0 auto; border: 3px solid #ced0d4; border-top-color: #0866ff; border-radius: 50%; }`,
    `${s("pdp")} { display: grid; grid-template-columns: minmax(0, 1fr) 380px; min-height: calc(100vh - 56px); margin: -16px -20px -80px; }`,
    `${s("pdpMedia")} { position: relative; display: grid; place-items: center; padding: 24px; background: #18191a; }`,
    `${s("pdpPhoto")} { max-width: 520px; max-height: 520px; border-radius: 4px; }`,
    `${s("pdpThumbs")} { display: flex; gap: 6px; margin-top: 12px; }`,
    `${s("pdpThumb")} { width: 52px; height: 52px; border-radius: 4px; background: #3a3b3c; }`,
    `${s("pdpArrow")} { position: absolute; top: 45%; width: 40px; height: 40px; border-radius: 50%; background: rgba(255,255,255,.8); display: grid; place-items: center; cursor: pointer; }`,
    `${s("heart")} { position: absolute; top: 20px; right: 20px; display: grid; place-items: center; width: 44px; height: 44px; border-radius: 50%; background: #fff; cursor: pointer; }`,
    `${s("heart")}[aria-pressed="true"] { background: #e7f3ff; }`,
    `${s("pdpPanel")} { position: relative; display: flex; flex-direction: column; box-sizing: border-box; height: calc(100vh - 56px); overflow: hidden; background: #fff; }`,
    `${s("pdpPanel")} > div:first-child { flex: 1; overflow: auto; padding: 16px 16px 24px; }`,
    `${s("pdpTitle")} { margin: 0 0 6px; font-size: 22px; }`,
    `${s("pdpPrice")} { font-size: 18px; font-weight: 600; }`,
    `${s("pdpListed")} { margin: 6px 0 12px; color: #65676b; font-size: 14px; }`,
    `${s("pdpActions")} { display: flex; gap: 8px; margin: 12px 0; }`,
    `${s("actionButton")}, ${s("actionPrimary")} { flex: 1; padding: 8px 10px; border-radius: 6px; background: #e4e6eb; font-weight: 600; text-align: center; cursor: pointer; user-select: none; }`,
    `${s("actionPrimary")} { background: #0866ff; color: #fff; }`,
    `${s("actionButton")}[aria-pressed="true"] { background: #e7f3ff; color: #0866ff; }`,
    `${s("pdpSection")} { padding: 12px 0; border-top: 1px solid #ced0d4; }`,
    `${s("pdpSectionTitle")} { margin: 0 0 8px; font-size: 17px; }`,
    `${s("detailRow")} { display: flex; gap: 12px; padding: 3px 0; }`,
    `${s("detailKey")} { width: 110px; color: #65676b; }`,
    `${s("seeMore")} { font-weight: 600; cursor: pointer; }`,
    `${s("distance")} { margin: 8px 0; color: #65676b; }`,
    `${s("mapFrame")} { width: 100%; height: 150px; border: 0; border-radius: 8px; }`,
    `${s("sellerCard")} { display: flex; gap: 10px; align-items: center; }`,
    `${s("sellerName")} { font-weight: 600; }`,
    `${s("sellerMeta")} { color: #65676b; font-size: 13px; }`,
    `${s("stickyBar")} { flex: none; padding: 12px 16px 16px; border-top: 1px solid #ced0d4; background: #fff; box-shadow: 0 -2px 6px rgba(0,0,0,.06); }`,
    `${s("messageLabel")} { display: block; margin-bottom: 6px; font-weight: 600; }`,
    `${s("messageBox")} { display: flex; gap: 8px; margin-bottom: 10px; }`,
    `${s("messageInput")} { flex: 1; padding: 8px 10px; border: 0; border-radius: 18px; background: #f0f2f5; }`,
    `${s("sendButton")} { padding: 8px 14px; border-radius: 6px; background: #0866ff; color: #fff; font-weight: 600; cursor: pointer; }`,
    `${s("offerButton")} { padding: 10px; border-radius: 6px; background: #e7f3ff; color: #0866ff; font-weight: 700; text-align: center; cursor: pointer; }`,
    `${s("receipt")} { margin-top: 10px; padding: 8px 10px; border-radius: 6px; background: #f0f2f5; font-size: 14px; }`,
    `${s("scrim")} { position: fixed; inset: 0; z-index: 70; display: grid; place-items: center; background: rgba(244,244,244,.8); }`,
    `${s("dialog")} { position: relative; width: min(500px, 92vw); box-sizing: border-box; border-radius: 8px; background: #fff; box-shadow: 0 12px 28px rgba(0,0,0,.2); }`,
    `${s("dialogTitle")} { margin: 0; padding: 16px 48px 12px 16px; border-bottom: 1px solid #ced0d4; font-size: 20px; }`,
    `${s("dialogBody")} { padding: 12px 16px; color: #1c1e21; }`,
    `${s("dialogFoot")} { display: flex; justify-content: flex-end; gap: 8px; padding: 12px 16px 16px; }`,
    `${s("buttonPrimary")}, ${s("buttonPlain")} { padding: 8px 14px; border-radius: 6px; font-weight: 600; cursor: pointer; user-select: none; }`,
    `${s("buttonPrimary")} { background: #0866ff; color: #fff; }`,
    `${s("buttonPlain")} { background: #e4e6eb; }`,
    `${s("closeX")} { position: absolute; top: 12px; right: 12px; display: grid; place-items: center; width: 34px; height: 34px; border-radius: 50%; background: #e4e6eb; cursor: pointer; }`,
    `${s("offerRow")} { display: flex; align-items: center; gap: 6px; margin: 6px 0 12px; }`,
    `${s("offerInput")}, ${s("textarea")} { flex: 1; box-sizing: border-box; width: 100%; padding: 9px 10px; border: 1px solid #ced0d4; border-radius: 6px; }`,
    `${s("fieldError")} { margin: 6px 0 0; color: #e41e3f; font-size: 13px; }`,
    `${s("honeypot")} { position: absolute; left: -10000px; top: auto; width: 1px; height: 1px; overflow: hidden; }`,
    `${s("chatDock")} { position: fixed; right: 20px; bottom: 0; z-index: 60; display: flex; flex-direction: column; width: 340px; height: 420px; border-radius: 8px 8px 0 0; background: #fff; box-shadow: 0 12px 28px rgba(0,0,0,.25); }`,
    `${s("chatDock")}[data-minimised] { height: 48px; width: 240px; }`,
    `${s("chatHead")} { display: flex; align-items: center; gap: 8px; padding: 6px 8px; border-bottom: 1px solid #ced0d4; }`,
    `${s("chatName")} { flex: 1; font-weight: 600; font-size: 14px; }`,
    `${s("chatControl")} { display: grid; place-items: center; width: 30px; height: 30px; border-radius: 50%; color: #0866ff; cursor: pointer; }`,
    `${s("chatBody")} { flex: 1; overflow: auto; padding: 10px; }`,
    `${s("chatBubble")} { max-width: 75%; margin: 4px 0; padding: 7px 11px; border-radius: 16px; background: #f0f0f0; font-size: 14px; }`,
    `${s("chatBubbleMine")} { margin-left: auto; background: #0866ff; color: #fff; }`,
    `${s("chatInput")} { margin: 8px; padding: 8px 12px; border-radius: 18px; background: #f0f2f5; color: #65676b; }`,
    `${s("toastRegion")} { position: fixed; left: 20px; bottom: 20px; z-index: 80; display: grid; gap: 8px; }`,
    `${s("toast")} { padding: 12px 16px; border-radius: 8px; background: #fff; box-shadow: 0 8px 20px rgba(0,0,0,.2); }`,
    `${s("pageHead")} { display: flex; align-items: center; gap: 14px; margin: 4px 0 14px; }`,
    `${s("pageTitle")} { margin: 0; font-size: 20px; }`,
    `${s("savedTotal")} { color: #65676b; }`,
    `${s("select")} { margin-left: auto; padding: 7px 10px; border: 1px solid #ced0d4; border-radius: 6px; background: #fff; }`,
    `${s("savedList")} { list-style: none; margin: 0; padding: 0; display: grid; gap: 8px; }`,
    `${s("savedRow")} { display: grid; grid-template-columns: 90px 1fr 40px; gap: 12px; align-items: center; padding: 10px; border-radius: 8px; background: #fff; }`,
    `${s("savedMedia")} { width: 90px; height: 90px; overflow: hidden; border-radius: 6px; }`,
    `${s("savedTitle")} { font-weight: 600; }`,
    `${s("savedPrice")} { font-weight: 600; }`,
    `${s("savedMeta")} { color: #65676b; font-size: 13px; }`,
    `${s("chip")} { margin-left: 6px; padding: 1px 7px; border-radius: 10px; background: #e6f4ea; color: #1e6b3a; font-size: 12px; }`,
    `${s("threadList")} { list-style: none; margin: 0; padding: 0; border-radius: 8px; background: #fff; }`,
    `${s("thread")} { display: flex; gap: 10px; align-items: center; padding: 10px 12px; border-bottom: 1px solid #f0f2f5; }`,
    `${s("threadName")} { font-weight: 600; }`,
    `${s("threadSnippet")} { color: #65676b; font-size: 13px; }`,
    `${s("emptyState")} { padding: 60px 20px; color: #65676b; text-align: center; }`,
    `${s("shopHead")} { padding: 16px 20px; background: #1d3b2a; color: #fff; font-size: 20px; font-weight: 700; }`,
    `${s("shopBody")} { max-width: 640px; margin: 20px auto; padding: 20px; border-radius: 8px; background: #fff; }`,
  ].join("\n");
}
