import type { StoreClasses } from "./classes.js";

/**
 * The store's stylesheet for one build. The first rules undo the lab's shared
 * page shell, which is centred and 48rem wide; a storefront is neither.
 *
 * Three pieces of geometry matter to anyone automating the page, and all
 * three are what the real thing does. The consent banner is fixed along the
 * bottom of the viewport and covers whatever is under it, which on a results
 * page is the pagination. The buy box sticks to the right-hand column, which
 * is exactly where the support chat opens its panel. And the app banner, when
 * it arrives, is in the flow at the top of the page, so everything below it
 * moves down by its height.
 */
export function storeStylesheet(css: StoreClasses): string {
  const c = css;
  return [
    `body { margin: 0; max-width: none; padding: 0; font: 14px/1.4 Arial, "Helvetica Neue", sans-serif; color: #0f1111; background: #eaeded; }`,
    `li { display: list-item; gap: 0; margin: 0; }`,
    `nav { display: block; gap: 0; }`,
    `label { display: inline; margin: 0; }`,
    `button, input, select, textarea { font: inherit; }`,
    `a { color: #2162a1; text-decoration: none; }`,
    `.${c.srOnly}, .${c.offscreen} { position: absolute; width: 1px; height: 1px; overflow: hidden; clip: rect(0 0 0 0); white-space: nowrap; }`,
    `.${c.honeypot} { position: absolute; left: -9999px; top: auto; width: 1px; height: 1px; opacity: 0; }`,
    `.${c.appBanner} { display: flex; align-items: center; gap: 12px; height: 64px; padding: 0 16px; background: #232f3e; color: #fff; }`,
    `.${c.header} { display: flex; align-items: center; gap: 14px; height: 60px; padding: 0 12px; background: #131921; color: #fff; }`,
    `.${c.logo} { color: #fff; font-size: 22px; font-weight: 700; letter-spacing: -.5px; }`,
    `.${c.deliver} { font-size: 12px; line-height: 1.2; color: #ccc; cursor: pointer; }`,
    `.${c.searchForm} { position: relative; display: flex; flex: 1; height: 40px; border-radius: 6px; overflow: visible; }`,
    `.${c.searchDept} { width: 64px; border: 0; border-radius: 6px 0 0 6px; background: #e6e6e6; }`,
    `.${c.searchInput} { flex: 1; border: 0; padding: 0 10px; }`,
    `.${c.searchSubmit} { width: 46px; border: 0; background: #febd69; cursor: pointer; }`,
    `.${c.searchExtra} { width: 40px; border: 0; background: #f3a847; cursor: pointer; }`,
    `.${c.headerLink} { color: #fff; font-size: 12px; line-height: 1.2; }`,
    `.${c.headerStrong} { display: block; font-size: 14px; font-weight: 700; }`,
    `.${c.cartLink} { position: relative; color: #fff; font-weight: 700; padding-left: 30px; }`,
    `.${c.cartBadge} { position: absolute; left: 12px; top: -10px; color: #f08804; font-size: 16px; }`,
    `.${c.subnav} { display: flex; gap: 14px; height: 38px; align-items: center; padding: 0 16px; background: #232f3e; }`,
    `.${c.subnavLink} { color: #fff; font-size: 13px; }`,
    `.${c.main} { padding: 12px 18px 160px; }`,
    `.${c.footer} { padding: 28px 18px 140px; background: #232f3e; color: #ddd; }`,
    `.${c.footerCols} { display: flex; gap: 60px; }`,
    `.${c.newsletter} { position: relative; display: flex; gap: 8px; margin-top: 18px; }`,
    `.${c.input} { padding: 6px 8px; border: 1px solid #a6a6a6; border-radius: 4px; }`,
    `.${c.button} { padding: 6px 12px; border: 1px solid #d5d9d9; border-radius: 8px; background: #fff; cursor: pointer; }`,
    `.${c.buttonPrimary} { border-color: #fcd200; background: #ffd814; border-radius: 20px; }`,
    `.${c.buttonSmall} { padding: 3px 10px; border: 1px solid #fcd200; border-radius: 16px; background: #ffd814; font-size: 12px; cursor: pointer; }`,
    `.${c.linkish} { color: #2162a1; cursor: pointer; font-size: 12px; }`,
    `.${c.consent} { position: fixed; left: 0; right: 0; bottom: 0; z-index: 50; padding: 16px 24px; background: #fff; box-shadow: 0 -4px 14px rgba(0,0,0,.2); }`,
    `.${c.consentActions} { display: flex; gap: 10px; margin-top: 10px; }`,
    `.${c.scrim} { position: fixed; inset: 0; z-index: 80; display: grid; place-items: center; background: rgba(15,17,17,.55); }`,
    `.${c.dialog} { width: min(440px, 92vw); border-radius: 8px; background: #fff; box-shadow: 0 16px 40px rgba(0,0,0,.35); }`,
    `.${c.dialogHead} { padding: 16px 18px 0; font-size: 17px; font-weight: 700; }`,
    `.${c.dialogBody} { padding: 10px 18px; }`,
    `.${c.dialogFoot} { display: flex; justify-content: flex-end; gap: 8px; padding: 10px 18px 16px; }`,
    `.${c.toast} { position: fixed; top: 110px; right: 20px; z-index: 90; padding: 10px 14px; border-radius: 6px; background: #067d62; color: #fff; }`,
    `.${c.popover} { position: absolute; z-index: 40; width: 260px; padding: 12px; border: 1px solid #ccc; border-radius: 6px; background: #fff; color: #0f1111; box-shadow: 0 6px 18px rgba(0,0,0,.2); }`,
    `.${c.suggestList} { position: absolute; top: 40px; left: 64px; right: 46px; z-index: 45; background: #fff; color: #0f1111; border: 1px solid #ccc; }`,
    `.${c.suggestItem} { padding: 6px 10px; cursor: pointer; }`,
    `.${c.searchLayout} { display: grid; grid-template-columns: 230px minmax(0, 1fr); gap: 18px; }`,
    `.${c.rail} { font-size: 13px; }`,
    `.${c.railGroup} { margin-bottom: 16px; }`,
    `.${c.railHeading} { margin: 0 0 6px; font-weight: 700; }`,
    `.${c.railLink} { display: flex; align-items: center; gap: 6px; padding: 2px 0; color: #0f1111; }`,
    `.${c.railBox} { display: inline-block; width: 13px; height: 13px; border: 1px solid #888; border-radius: 2px; }`,
    `.${c.railBoxOn} { background: #007185; border-color: #007185; }`,
    `.${c.priceForm} { display: flex; gap: 4px; align-items: center; }`,
    `.${c.priceInput} { width: 56px; padding: 4px; border: 1px solid #888; border-radius: 4px; }`,
    `.${c.resultsBar} { display: flex; align-items: center; justify-content: space-between; padding: 8px 12px; margin-bottom: 10px; background: #fff; }`,
    `.${c.sortSelect} { padding: 3px 6px; border-radius: 8px; background: #f0f2f2; }`,
    `.${c.results} { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 12px; }`,
    `.${c.card} { position: relative; padding: 10px; background: #fff; }`,
    `.${c.skeleton} { height: 330px; background: #fff; }`,
    `.${c.skelBlock} { height: 14px; margin: 10px; border-radius: 4px; background: linear-gradient(90deg, #eee, #f6f6f6, #eee); }`,
    `.${c.cardImg} { display: block; width: 100%; aspect-ratio: 1; object-fit: contain; background: #f7f7f7; }`,
    `.${c.brandLine} { font-weight: 700; font-size: 13px; }`,
    `.${c.cardTitle} { margin: 6px 0; font-size: 14px; font-weight: 400; line-height: 1.3; }`,
    `.${c.titleLink} { color: #0f1111; display: -webkit-box; -webkit-line-clamp: 4; -webkit-box-orient: vertical; overflow: hidden; }`,
    `.${c.reviews} { display: flex; gap: 6px; align-items: center; font-size: 13px; }`,
    `.${c.stars} { color: #de7921; }`,
    `.${c.ratingCount} { color: #2162a1; }`,
    `.${c.social} { font-size: 12px; color: #565959; }`,
    `.${c.priceRow} { margin-top: 6px; }`,
    `.${c.price} { color: #0f1111; font-size: 21px; }`,
    `.${c.priceSym}, .${c.priceFrac} { font-size: 12px; vertical-align: top; }`,
    `.${c.priceDec} { display: none; }`,
    `.${c.listPrice} { margin-left: 6px; font-size: 12px; color: #565959; }`,
    `.${c.strike} { text-decoration: line-through; }`,
    `.${c.coupon} { font-size: 12px; }`,
    `.${c.couponBadge} { padding: 1px 4px; background: #7fda69; color: #0f1111; }`,
    `.${c.delivery} { font-size: 12px; margin: 4px 0; }`,
    `.${c.plusBadge} { display: inline-block; width: 42px; height: 12px; margin-right: 4px; background: linear-gradient(90deg, #1a98ff, #0073e6); border-radius: 2px; vertical-align: middle; }`,
    `.${c.adLabel} { font-size: 12px; color: #565959; }`,
    `.${c.adInfo} { cursor: pointer; }`,
    `.${c.carousel}, .${c.widget} { grid-column: 1 / -1; padding: 12px; background: #fff; }`,
    `.${c.carouselHead} { margin: 0 0 8px; font-size: 16px; font-weight: 700; }`,
    `.${c.carouselTrack} { display: flex; gap: 12px; list-style: none; margin: 0; padding: 0; overflow-x: auto; }`,
    `.${c.carouselItem} { flex: 0 0 220px; }`,
    `.${c.sentinel} { grid-column: 1 / -1; padding: 24px; text-align: center; color: #565959; background: #fff; }`,
    `.${c.pagination} { display: flex; justify-content: flex-end; gap: 4px; margin: 18px 0; padding-right: 40px; }`,
    `.${c.pageLink}, .${c.pageCurrent}, .${c.pageDisabled}, .${c.pageGap} { padding: 8px 12px; border: 1px solid #d5d9d9; background: #fff; color: #0f1111; }`,
    `.${c.pageCurrent} { border-color: #0f1111; font-weight: 700; }`,
    `.${c.pageDisabled} { color: #aaa; }`,
    `.${c.noResults} { padding: 30px; background: #fff; }`,
    `.${c.wheel} { text-align: center; }`,
    `.${c.wheelDisc} { width: 180px; height: 180px; margin: 10px auto; border-radius: 50%; background: conic-gradient(#ff9900 0 25%, #146eb4 0 50%, #ffd814 0 75%, #067d62 0); }`,
    `.${c.productLayout} { display: grid; grid-template-columns: 38% minmax(0, 1fr) 300px; gap: 20px; padding: 10px; background: #fff; }`,
    `.${c.galleryMain} { width: 100%; aspect-ratio: 1; object-fit: contain; }`,
    `.${c.thumbs} { display: flex; gap: 6px; }`,
    `.${c.productTitle} { margin: 0; font-size: 22px; font-weight: 400; line-height: 1.3; }`,
    `.${c.pick} { display: inline-block; padding: 2px 6px; background: #232f3e; color: #fff; font-size: 12px; }`,
    `.${c.priceBlock} { margin: 10px 0; }`,
    `.${c.savings} { color: #cc0c39; font-size: 22px; margin-right: 6px; }`,
    `.${c.variationLabel} { margin: 10px 0 4px; }`,
    `.${c.swatchList}, .${c.tileList} { display: flex; gap: 8px; list-style: none; margin: 0; padding: 0; }`,
    `.${c.swatch} { width: 44px; height: 44px; border: 1px solid #aaa; border-radius: 4px; cursor: pointer; }`,
    `.${c.swatchOn}, .${c.tileOn} { outline: 2px solid #007185; }`,
    `.${c.swatchOff} { opacity: .35; background-image: linear-gradient(135deg, transparent 48%, #999 50%, transparent 52%); }`,
    `.${c.tile} { padding: 6px 10px; border: 1px solid #aaa; border-radius: 6px; cursor: pointer; }`,
    `.${c.tilePrice} { display: block; font-size: 12px; color: #565959; }`,
    `.${c.buyBox} { position: sticky; top: 110px; align-self: start; padding: 14px; border: 1px solid #d5d9d9; border-radius: 8px; }`,
    `.${c.buyPrice} { font-size: 26px; }`,
    `.${c.stock} { color: #007600; font-size: 18px; }`,
    `.${c.stockLow} { color: #b12704; font-size: 16px; }`,
    `.${c.addButton}, .${c.buyNowButton} { display: block; width: 100%; margin: 8px 0; padding: 8px; border: 0; border-radius: 20px; cursor: pointer; }`,
    `.${c.addButton} { background: #ffd814; }`,
    `.${c.buyNowButton} { background: #ffa41c; }`,
    `.${c.protection} { margin: 8px 0; font-size: 13px; }`,
    `.${c.soldBy} { font-size: 12px; color: #565959; }`,
    `.${c.otherSellers} { margin-top: 10px; padding-top: 10px; border-top: 1px solid #ddd; font-size: 13px; }`,
    `.${c.sidePanel}, .${c.sideSheet} { position: fixed; top: 0; right: 0; bottom: 0; z-index: 70; width: 420px; overflow: auto; padding: 18px; background: #fff; box-shadow: -8px 0 24px rgba(0,0,0,.25); }`,
    `.${c.offerRow} { display: flex; justify-content: space-between; align-items: center; padding: 10px 0; border-bottom: 1px solid #eee; }`,
    `.${c.fbt}, .${c.related}, .${c.specs}, .${c.reviewsBlock} { margin-top: 16px; padding: 14px; background: #fff; }`,
    `.${c.fbtRow} { display: flex; gap: 10px; align-items: center; }`,
    `.${c.loginWall} { padding: 12px; background: #f7fafa; border: 1px solid #d5d9d9; }`,
    `.${c.spinner} { display: inline-block; width: 14px; height: 14px; border: 2px solid #ccc; border-top-color: #333; border-radius: 50%; animation: ba-spin .8s linear infinite; }`,
    `@keyframes ba-spin { to { transform: rotate(360deg); } }`,
    `.${c.cartLayout} { display: grid; grid-template-columns: minmax(0, 1fr) 300px; gap: 18px; }`,
    `.${c.cartMain} { padding: 18px; background: #fff; }`,
    `.${c.cartRow} { position: relative; display: grid; grid-template-columns: 26px 120px minmax(0, 1fr) 110px; gap: 12px; padding: 14px 0; border-bottom: 1px solid #ddd; }`,
    `.${c.cartTitle} { color: #0f1111; font-size: 16px; }`,
    `.${c.variationLine} { list-style: none; margin: 4px 0; padding: 0; font-size: 12px; }`,
    `.${c.cartActions} { display: flex; flex-wrap: wrap; align-items: center; gap: 10px; margin-top: 8px; font-size: 12px; }`,
    `.${c.qtyControl} { display: inline-flex; align-items: center; border: 3px solid #ffd814; border-radius: 16px; }`,
    `.${c.qtyButton} { display: inline-block; width: 26px; text-align: center; cursor: pointer; }`,
    `.${c.qtyValue} { min-width: 22px; text-align: center; font-weight: 700; }`,
    `.${c.rowPrice} { text-align: right; font-size: 18px; font-weight: 700; }`,
    `.${c.subtotal} { text-align: right; font-size: 18px; }`,
    `.${c.cartAside} { align-self: start; padding: 18px; background: #fff; }`,
    `.${c.savedGrid} { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 12px; }`,
    `.${c.rowError} { color: #b12704; font-size: 13px; }`,
    `.${c.rowBusy} { position: absolute; inset: 0; display: grid; place-items: center; background: rgba(255,255,255,.7); }`,
    `.${c.checkoutLayout} { display: grid; grid-template-columns: minmax(0, 1fr) 300px; gap: 18px; max-width: 1100px; margin: 0 auto; }`,
    `.${c.section} { margin-bottom: 14px; padding: 16px; border: 1px solid #d5d9d9; border-radius: 8px; background: #fff; }`,
    `.${c.sectionHead} { display: flex; justify-content: space-between; font-size: 16px; font-weight: 700; }`,
    `.${c.optionList} { list-style: none; margin: 8px 0 0; padding: 0; }`,
    `.${c.optionRow} { padding: 6px 0; }`,
    `.${c.upsell} { padding: 12px; border: 1px solid #1a98ff; border-radius: 8px; background: #f0f8ff; }`,
    `.${c.summary} { align-self: start; padding: 16px; border: 1px solid #d5d9d9; border-radius: 8px; background: #fff; }`,
    `.${c.summaryRow} { display: flex; justify-content: space-between; font-size: 13px; }`,
    `.${c.summaryTotal} { display: flex; justify-content: space-between; margin-top: 8px; padding-top: 8px; border-top: 1px solid #ddd; color: #b12704; font-size: 18px; font-weight: 700; }`,
    `.${c.placeButton} { display: block; width: 100%; margin: 10px 0; padding: 9px; border: 0; border-radius: 20px; background: #ffd814; cursor: pointer; text-align: center; }`,
    `.${c.paymentFrame} { width: 100%; height: 190px; border: 1px solid #ddd; }`,
    `.${c.confirmBox} { max-width: 900px; margin: 0 auto; padding: 20px; background: #fff; border-left: 6px solid #067d62; }`,
    `.${c.confirmLine} { margin: 6px 0; }`,
    `.${c.challengePage} { display: grid; place-items: start center; min-height: 100vh; padding-top: 60px; background: #fff; }`,
    `.${c.challengeBox} { width: 420px; padding: 18px; border: 1px solid #ddd; border-radius: 6px; }`,
    `.${c.captchaCanvas} { display: block; margin: 10px 0; border: 1px solid #ccc; background: #f4f4f4; }`,
    `.${c.challengeError} { color: #c40000; }`,
    `.${c.hero} { height: 240px; margin-bottom: 14px; overflow: hidden; background: linear-gradient(120deg, #7fb3d5, #f5d6a8); }`,
    `.${c.heroSlide} { padding: 40px; font-size: 28px; font-weight: 700; }`,
    `.${c.tiles} { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 16px; }`,
    `.${c.tile2} { padding: 16px; background: #fff; }`,
    `.${c.tileHead} { margin: 0 0 10px; font-size: 19px; font-weight: 700; }`,
  ].join("\n");
}
