import { readFile } from "node:fs/promises";
import path from "node:path";

export type FluxIQTargetMode = "isolated" | "existing" | "clone";

export type FluxIQTestCredentials = {
  username: string;
  password: string;
  authorizationPin?: string;
  totp?: string;
};

export type IsolatedTargetConfiguration = {
  mode: "isolated";
  credentials?: FluxIQTestCredentials;
};

export type ExistingTargetConfiguration = {
  mode: "existing";
  baseUrl: string;
  gatewayUrl?: string;
  projectId: string;
  flowId: string;
  credentials: FluxIQTestCredentials & { authorizationPin: string };
  freshLogin?: true;
};

export type CloneSourceConfiguration = {
  baseUrl: string;
  projectId: string;
  flowId: string;
  credentials: FluxIQTestCredentials;
};

export type CloneTargetConfiguration = {
  mode: "clone";
  source: CloneSourceConfiguration;
  /** Destination bootstrap credentials are generated by the isolated topology. */
  credentials?: never;
  freshLogin?: true;
};

export type FluxIQTargetConfiguration = IsolatedTargetConfiguration | ExistingTargetConfiguration | CloneTargetConfiguration;

export type ResolveTargetConfigurationInput = {
  cliTarget?: FluxIQTargetMode;
  cliFlowId?: string;
  cliFreshLogin?: boolean;
  env: NodeJS.ProcessEnv;
};

export type AuthScopeConfiguration = { mode: "existing" | "clone"; origin: string; username: string };
export type CloneCacheScopeConfiguration = { origin: string; username: string; projectId: string; flowId: string };

const existingKeys = ["FLUXIQ_TEST_BASE_URL", "FLUXIQ_TEST_GATEWAY_URL", "FLUXIQ_TEST_PROJECT_ID", "FLUXIQ_TEST_FLOW_ID"] as const;

export function resolveTargetConfiguration(input: ResolveTargetConfigurationInput): FluxIQTargetConfiguration {
  const envMode = optionalText(input.env.FLUXIQ_TEST_TARGET, "FLUXIQ_TEST_TARGET") as FluxIQTargetMode | undefined;
  if (envMode !== undefined && envMode !== "isolated" && envMode !== "existing" && envMode !== "clone") throw new Error("FLUXIQ_TEST_TARGET must be isolated, existing, or clone");
  if (input.cliTarget && envMode && input.cliTarget !== envMode) throw new Error(`--target ${input.cliTarget} conflicts with FLUXIQ_TEST_TARGET=${envMode}`);
  const mode = input.cliTarget ?? envMode ?? "isolated";
  const configuredExistingKeys = existingKeys.filter(key => optionalText(input.env[key], key) !== undefined);
  if (mode === "isolated") {
    if (configuredExistingKeys.length || input.cliFlowId || input.cliFreshLogin) throw new Error(`isolated target cannot use existing-install configuration: ${[...configuredExistingKeys, ...(input.cliFlowId ? ["--flow"] : []), ...(input.cliFreshLogin ? ["--fresh-login"] : [])].join(", ")}`);
    const username = optionalText(input.env.FLUXIQ_TEST_USERNAME, "FLUXIQ_TEST_USERNAME");
    const password = optionalText(input.env.FLUXIQ_TEST_PASSWORD, "FLUXIQ_TEST_PASSWORD");
    if (Boolean(username) !== Boolean(password)) throw new Error("isolated configured credentials require both FLUXIQ_TEST_USERNAME and FLUXIQ_TEST_PASSWORD");
    return { mode, ...(username && password ? { credentials: credentials(input.env, username, password, false) } : {}) };
  }

  const baseUrl = httpOrigin(required(input.env.FLUXIQ_TEST_BASE_URL, "FLUXIQ_TEST_BASE_URL"), "FLUXIQ_TEST_BASE_URL");
  const gatewayValue = optionalText(input.env.FLUXIQ_TEST_GATEWAY_URL, "FLUXIQ_TEST_GATEWAY_URL");
  const projectId = required(input.env.FLUXIQ_TEST_PROJECT_ID, "FLUXIQ_TEST_PROJECT_ID");
  const flowId = input.cliFlowId ? nonEmpty(input.cliFlowId, "--flow") : required(input.env.FLUXIQ_TEST_FLOW_ID, "FLUXIQ_TEST_FLOW_ID");
  const username = required(input.env.FLUXIQ_TEST_USERNAME, "FLUXIQ_TEST_USERNAME");
  const password = required(input.env.FLUXIQ_TEST_PASSWORD, "FLUXIQ_TEST_PASSWORD");
  const resolvedCredentials = credentials(input.env, username, password, mode === "existing");
  if (mode === "clone") {
    return {
      mode,
      source: { baseUrl, projectId, flowId, credentials: resolvedCredentials },
      ...(input.cliFreshLogin ? { freshLogin: true as const } : {}),
    };
  }
  if (!resolvedCredentials.authorizationPin) throw new Error("FLUXIQ_TEST_PIN is required for an existing target");
  return {
    mode,
    baseUrl,
    ...(gatewayValue ? { gatewayUrl: requireSecureGatewayUrl(gatewayValue, "FLUXIQ_TEST_GATEWAY_URL") } : {}),
    projectId,
    flowId,
    credentials: resolvedCredentials as FluxIQTestCredentials & { authorizationPin: string },
    ...(input.cliFreshLogin ? { freshLogin: true as const } : {}),
  };
}

export function resolveAuthScopeConfiguration(env: NodeJS.ProcessEnv): AuthScopeConfiguration {
  const mode = optionalText(env.FLUXIQ_TEST_TARGET, "FLUXIQ_TEST_TARGET");
  if (mode !== "existing" && mode !== "clone") throw new Error("auth status and clear require FLUXIQ_TEST_TARGET=existing or clone");
  const baseUrl = httpOrigin(requiredForAuth(env.FLUXIQ_TEST_BASE_URL, "FLUXIQ_TEST_BASE_URL"), "FLUXIQ_TEST_BASE_URL");
  const username = requiredForAuth(env.FLUXIQ_TEST_USERNAME, "FLUXIQ_TEST_USERNAME");
  return { mode, origin: new URL(baseUrl).origin, username };
}

export function resolveCloneCacheScopeConfiguration(env: NodeJS.ProcessEnv): CloneCacheScopeConfiguration {
  const auth = resolveAuthScopeConfiguration(env);
  if (auth.mode !== "clone") throw new Error("clone-cache controls require FLUXIQ_TEST_TARGET=clone");
  return { origin: auth.origin, username: auth.username, projectId: required(env.FLUXIQ_TEST_PROJECT_ID, "FLUXIQ_TEST_PROJECT_ID"), flowId: required(env.FLUXIQ_TEST_FLOW_ID, "FLUXIQ_TEST_FLOW_ID") };
}

export async function loadTestEnvironment(repositoryRoot: string, processEnvironment: NodeJS.ProcessEnv): Promise<NodeJS.ProcessEnv> {
  const fromFile: NodeJS.ProcessEnv = {};
  for (const name of [".env", ".env.local"]) Object.assign(fromFile, await readEnvironmentFile(path.join(repositoryRoot, name)));
  return { ...fromFile, ...processEnvironment };
}

export function parseEnvironmentFile(contents: string): NodeJS.ProcessEnv {
  const result: NodeJS.ProcessEnv = {};
  for (const [lineIndex, sourceLine] of contents.replace(/^\uFEFF/u, "").split(/\r?\n/u).entries()) {
    const line = sourceLine.trim();
    if (!line || line.startsWith("#")) continue;
    const match = /^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/u.exec(line);
    if (!match) throw new Error(`Invalid environment assignment on line ${lineIndex + 1}`);
    result[match[1]!] = parseEnvironmentValue(match[2]!, lineIndex + 1);
  }
  return result;
}

async function readEnvironmentFile(filePath: string): Promise<NodeJS.ProcessEnv> {
  try { return parseEnvironmentFile(await readFile(filePath, "utf8")); }
  catch (error) {
    if (typeof error === "object" && error !== null && "code" in error && error.code === "ENOENT") return {};
    throw error;
  }
}

function parseEnvironmentValue(value: string, line: number): string {
  const trimmed = value.trim();
  if (!trimmed.startsWith("\"") && !trimmed.startsWith("'")) return trimmed.replace(/\s+#.*$/u, "").trim();
  const quote = trimmed[0]!;
  if (trimmed.length < 2 || trimmed.at(-1) !== quote) throw new Error(`Unterminated quoted environment value on line ${line}`);
  const body = trimmed.slice(1, -1);
  return quote === "\"" ? body.replaceAll("\\n", "\n").replaceAll("\\r", "\r").replaceAll('\\"', '"').replaceAll("\\\\", "\\") : body;
}

function credentials(env: NodeJS.ProcessEnv, username: string, password: string, requirePin: boolean): FluxIQTestCredentials {
  const authorizationPin = optionalText(env.FLUXIQ_TEST_PIN, "FLUXIQ_TEST_PIN");
  const totp = optionalText(env.FLUXIQ_TEST_TOTP, "FLUXIQ_TEST_TOTP");
  if (requirePin && !authorizationPin) throw new Error("FLUXIQ_TEST_PIN is required for an existing target");
  return { username, password, ...(authorizationPin ? { authorizationPin } : {}), ...(totp ? { totp } : {}) };
}

function required(value: string | undefined, name: string): string { const resolved = optionalText(value, name); if (!resolved) throw new Error(`${name} is required for an existing or clone target`); return resolved; }
function requiredForAuth(value: string | undefined, name: string): string { const resolved = optionalText(value, name); if (!resolved) throw new Error(`${name} is required for auth status and clear`); return resolved; }
function optionalText(value: string | undefined, name: string): string | undefined { if (value === undefined) return undefined; return nonEmpty(value, name); }
function nonEmpty(value: string, name: string): string { const resolved = value.trim(); if (!resolved) throw new Error(`${name} must not be empty`); if (/\r|\n/u.test(resolved)) throw new Error(`${name} must be a single line`); return resolved; }
function httpOrigin(value: string, name: string): string {
  const normalized = normalizedUrl(value, name, ["http:", "https:"]);
  const parsed = new URL(normalized);
  if (parsed.pathname !== "/") throw new Error(`${name} must be an exact origin without a path`);
  return parsed.origin;
}
export function requireSecureGatewayUrl(value: string, name = "FluxIQ gateway URL"): string {
  const normalized = normalizedUrl(value, name, ["ws:", "wss:"]);
  const parsed = new URL(normalized);
  if (parsed.protocol === "ws:" && !isLoopbackHost(parsed.hostname)) throw new Error(`${name} must use wss:// unless it targets loopback`);
  return normalized;
}
function isLoopbackHost(hostname: string): boolean {
  return hostname === "localhost" || hostname.endsWith(".localhost") || hostname === "[::1]" || /^127(?:\.\d{1,3}){3}$/u.test(hostname);
}
function normalizedUrl(value: string, name: string, protocols: string[]): string {
  let parsed: URL;
  try { parsed = new URL(value); } catch { throw new Error(`${name} must be an absolute URL`); }
  if (!protocols.includes(parsed.protocol)) throw new Error(`${name} must use ${protocols.join(" or ")}`);
  if (parsed.username || parsed.password) throw new Error(`${name} must not contain credentials`);
  if (parsed.search || parsed.hash) throw new Error(`${name} must not contain a query or fragment`);
  return parsed.toString().replace(/\/$/u, "");
}
