import type { PhotoLook } from "./classes.js";

/**
 * The emitted stylesheet. The first rules undo the lab's shared page shell
 * (centred, 48rem wide); an application shell is neither.
 *
 * The geometry is load-bearing. A post, on its own page or in the grid's
 * modal, puts its action row near the bottom right of a 1280 by 720 window,
 * and the messages dock, expanded, occupies the bottom right corner -- so the
 * bookmark, the "Load more comments" control and the modal's Next arrow sit
 * under it until it is collapsed, as they do on the site this imitates.
 */
export function photoStylesheet({ hook: h }: PhotoLook): string {
  const s = (role: keyof PhotoLook["hook"]) => `.${h[role]}`;
  return [
    `body { margin: 0; max-width: none; padding: 0; font: 14px/1.4 -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; color: #0f1419; background: #fff; }`,
    `li { display: list-item; gap: 0; margin: 0; } nav { display: block; gap: 0; } label { display: inline; margin: 0; }`,
    `button, input, textarea { font: inherit; } a { color: inherit; text-decoration: none; } ul { list-style: none; margin: 0; padding: 0; }`,
    `[role="button"] { cursor: pointer; user-select: none; }`,
    `[hidden] { display: none !important; }`,
    `${s("app")} { display: grid; grid-template-columns: 244px minmax(0, 1fr); min-height: 100vh; }`,
    `${s("nav")} { position: fixed; top: 0; left: 0; bottom: 0; width: 244px; box-sizing: border-box; padding: 26px 12px; border-right: 1px solid #dbdbdb; background: #fff; z-index: 20; }`,
    `${s("navBrand")} { display: block; padding: 0 12px 26px; font: italic 600 24px/1 Georgia, serif; }`,
    `${s("navItem")} { position: relative; display: flex; align-items: center; gap: 16px; padding: 12px; margin: 2px 0; border-radius: 8px; }`,
    `${s("navItem")}:hover { background: #f2f2f2; }`,
    `${s("navIcon")} { width: 24px; height: 24px; flex: none; }`,
    `${s("navBadge")} { position: absolute; left: 26px; top: 6px; min-width: 18px; height: 18px; padding: 0 4px; box-sizing: border-box; border-radius: 9px; background: #ff3040; color: #fff; font-size: 11px; line-height: 18px; text-align: center; }`,
    `${s("main")} { grid-column: 2; min-width: 0; }`,
    `${s("feed")} { display: grid; grid-template-columns: minmax(0, 470px) 320px; gap: 64px; justify-content: center; padding: 24px 16px 120px; }`,
    `${s("stories")} { display: flex; gap: 14px; overflow: hidden; padding: 8px 0 20px; }`,
    `${s("story")} { display: grid; justify-items: center; gap: 4px; width: 66px; font-size: 12px; }`,
    `${s("storyRing")} { width: 58px; height: 58px; border-radius: 50%; padding: 2px; box-sizing: border-box; background: conic-gradient(#feda75, #d62976, #962fbf, #feda75); }`,
    `${s("card")} { border-bottom: 1px solid #dbdbdb; padding-bottom: 14px; margin-bottom: 18px; }`,
    `${s("cardHead")} { display: flex; align-items: center; gap: 10px; padding: 8px 0; }`,
    `${s("avatar")} { width: 32px; height: 32px; border-radius: 50%; flex: none; display: inline-block; }`,
    `${s("avatarLarge")} { width: 150px; height: 150px; border-radius: 50%; flex: none; }`,
    `${s("handle")} { font-weight: 600; }`,
    `${s("verified")} { width: 12px; height: 12px; color: #0095f6; vertical-align: -1px; margin-left: 3px; }`,
    `${s("meta")} { color: #737373; font-size: 12px; }`,
    `${s("media")} { position: relative; overflow: hidden; background: #efefef; border-radius: 4px; }`,
    `${s("mediaImg")} { display: block; width: 100%; aspect-ratio: 1 / 1; object-fit: cover; }`,
    `${s("carouselArrow")} { position: absolute; top: 50%; width: 30px; height: 30px; margin-top: -15px; border-radius: 50%; background: rgba(255,255,255,.85); display: grid; place-items: center; }`,
    `${s("dots")} { display: flex; justify-content: center; gap: 4px; padding: 6px 0; } ${s("dot")} { width: 6px; height: 6px; border-radius: 50%; background: #c7c7c7; }`,
    `${s("actions")} { position: relative; display: flex; align-items: center; gap: 12px; padding: 6px 0; }`,
    `${s("iconButton")} { display: inline-grid; place-items: center; width: 32px; height: 32px; }`,
    `${s("iconButton")} svg { width: 24px; height: 24px; }`,
    `${s("likes")} { font-weight: 600; margin: 2px 0; }`,
    `${s("caption")} { margin: 4px 0; white-space: normal; }`,
    `${s("more")} { color: #737373; } ${s("commentsLink")} { color: #737373; display: block; margin: 4px 0; }`,
    `${s("composer")} { display: flex; align-items: center; gap: 8px; border-top: 1px solid #efefef; padding: 10px 16px; min-height: 52px; box-sizing: border-box; }`,
    `${s("composerInput")} { flex: 1; border: 0; outline: 0; resize: none; height: 20px; }`,
    `${s("postButton")} { color: #0095f6; font-weight: 600; } ${s("postButton")}[aria-disabled="true"] { opacity: .3; }`,
    `${s("skeleton")} { background: linear-gradient(90deg, #efefef, #fafafa, #efefef); background-size: 200% 100%; animation: fl-shimmer 1.2s infinite; border-radius: 4px; min-height: 18px; margin: 6px 0; }`,
    `@keyframes fl-shimmer { from { background-position: 200% 0; } to { background-position: -200% 0; } }`,
    `${s("spinner")} { width: 28px; height: 28px; border: 3px solid #dbdbdb; border-top-color: #737373; border-radius: 50%; animation: fl-spin .8s linear infinite; margin: 12px auto; }`,
    `@keyframes fl-spin { to { transform: rotate(360deg); } }`,
    `${s("sponsored")} { color: #737373; font-size: 12px; display: block; }`,
    `${s("suggested")} { border: 1px solid #efefef; border-radius: 8px; padding: 12px; margin-bottom: 18px; }`,
    `${s("rail")} { padding-top: 12px; } ${s("railHead")} { display: flex; justify-content: space-between; color: #737373; font-weight: 600; margin: 16px 0 8px; }`,
    `${s("railRow")} { display: flex; align-items: center; gap: 10px; padding: 6px 0; }`,
    `${s("follow")} { margin-left: auto; color: #0095f6; font-weight: 600; font-size: 12px; }`,
    `${s("linkButton")} { display: inline-block; color: #0095f6; font-weight: 600; }`,
    `${s("profile")} { max-width: 935px; margin: 0 auto; padding: 30px 20px 120px; }`,
    `${s("profileHead")} { display: flex; gap: 80px; align-items: flex-start; padding: 0 40px 40px; border-bottom: 1px solid #dbdbdb; }`,
    `${s("profileStats")} { display: flex; gap: 36px; margin: 18px 0; }`,
    `${s("bio")} { white-space: pre-line; }`,
    `${s("primary")} { display: inline-block; padding: 7px 16px; border-radius: 8px; background: #0095f6; color: #fff; font-weight: 600; text-align: center; }`,
    `${s("secondary")} { display: inline-block; padding: 7px 16px; border-radius: 8px; background: #efefef; font-weight: 600; text-align: center; }`,
    `${s("tabs")} { display: flex; justify-content: center; gap: 60px; } ${s("tab")} { padding: 16px 0; font-size: 12px; letter-spacing: 1px; text-transform: uppercase; color: #737373; } ${s("tab")}[aria-selected="true"] { color: #0f1419; border-top: 1px solid #0f1419; }`,
    `${s("grid")} { display: grid; grid-template-columns: repeat(3, 1fr); gap: 4px; }`,
    `${s("cell")} { position: relative; display: block; }`,
    `${s("cellImg")} { display: block; width: 100%; aspect-ratio: 1 / 1; object-fit: cover; }`,
    `${s("cellBadge")} { position: absolute; top: 8px; right: 8px; color: #fff; width: 20px; height: 20px; }`,
    `${s("cellOverlay")} { position: absolute; inset: 0; display: flex; align-items: center; justify-content: center; gap: 22px; color: #fff; font-weight: 700; background: rgba(0,0,0,.3); opacity: 0; }`,
    `${s("cell")}:hover ${s("cellOverlay")} { opacity: 1; }`,
    `${s("wall")} { position: relative; margin: 20px 0; } ${s("wallCard")} { max-width: 380px; margin: 0 auto; padding: 24px; border: 1px solid #dbdbdb; border-radius: 12px; text-align: center; display: grid; gap: 12px; }`,
    `${s("article")} { display: grid; grid-template-columns: minmax(0, 1fr) 400px; max-width: 1000px; height: calc(100vh - 40px); margin: 20px auto; border: 1px solid #dbdbdb; background: #fff; box-sizing: border-box; }`,
    `${s("articleMedia")} { position: relative; background: #000; display: grid; place-items: center; overflow: hidden; }`,
    `${s("articleSide")} { display: flex; flex-direction: column; min-height: 0; border-left: 1px solid #efefef; }`,
    `${s("thread")} { flex: 1; overflow-y: auto; padding: 12px 16px; min-height: 0; }`,
    `${s("comment")} { margin: 0 0 14px; } ${s("commentBody")} { display: flex; gap: 10px; } ${s("commentMeta")} { display: flex; gap: 12px; color: #737373; font-size: 12px; margin-top: 4px; }`,
    `${s("comment")} h3 { display: inline; font-size: 14px; margin: 0 6px 0 0; }`,
    `${s("replies")} { margin: 10px 0 0 42px; } ${s("repliesToggle")} { color: #737373; font-size: 12px; font-weight: 600; margin: 8px 0 0 42px; }`,
    `${s("loadMore")} { display: grid; place-items: center; width: 32px; height: 32px; margin: 8px auto 4px; border: 1px solid #0f1419; border-radius: 50%; }`,
    `${s("scrim")} { position: fixed; inset: 0; background: rgba(0,0,0,.65); z-index: 60; display: grid; place-items: center; }`,
    `${s("modal")} { position: fixed; inset: 0; background: rgba(0,0,0,.65); z-index: 40; }`,
    `${s("modal")} ${s("article")} { position: absolute; top: 40px; left: 50%; transform: translateX(-50%); width: min(1100px, calc(100vw - 160px)); max-width: none; height: calc(100vh - 80px); margin: 0; }`,
    `${s("modalNav")} { position: absolute; top: 50%; margin-top: -20px; width: 40px; height: 40px; border-radius: 50%; background: #fff; display: grid; place-items: center; }`,
    `${s("close")} { position: absolute; top: 12px; right: 16px; color: #fff; }`,
    `${s("dialog")} { width: min(400px, 92vw); max-height: 80vh; overflow: auto; background: #fff; border-radius: 12px; }`,
    `${s("dialogHead")} { position: relative; padding: 14px 44px; border-bottom: 1px solid #dbdbdb; text-align: center; font-weight: 600; font-size: 16px; }`,
    `${s("dialogBody")} { padding: 16px; display: grid; gap: 10px; }`,
    `${s("dialogRow")} { display: flex; align-items: center; gap: 12px; padding: 8px 16px; }`,
    `${s("check")} { margin-left: auto; width: 22px; height: 22px; }`,
    `${s("input")} { width: 100%; box-sizing: border-box; padding: 9px 10px; border: 1px solid #dbdbdb; border-radius: 6px; background: #fafafa; }`,
    `${s("toast")} { position: fixed; left: 50%; bottom: 24px; transform: translateX(-50%); padding: 12px 18px; border-radius: 8px; background: #262626; color: #fff; z-index: 90; }`,
    `${s("popover")} { position: absolute; z-index: 30; right: 0; bottom: 44px; padding: 10px 14px; border-radius: 8px; background: #fff; box-shadow: 0 4px 18px rgba(0,0,0,.2); display: flex; gap: 14px; align-items: center; white-space: nowrap; }`,
    `${s("banner")} { position: fixed; left: 244px; right: 0; bottom: 0; z-index: 25; display: flex; align-items: center; gap: 16px; padding: 12px 20px; background: #fafafa; border-top: 1px solid #dbdbdb; }`,
    `${s("consent")} { width: min(560px, 92vw); background: #fff; border-radius: 12px; padding: 24px; display: grid; gap: 12px; }`,
    `${s("consentActions")} { display: grid; gap: 8px; }`,
    `${s("search")} { position: fixed; top: 0; bottom: 0; left: 72px; width: 400px; z-index: 30; background: #fff; border-radius: 0 16px 16px 0; box-shadow: 4px 0 24px rgba(0,0,0,.15); padding: 20px 0; overflow: auto; }`,
    `${s("searchInput")} { margin: 12px 16px 20px; width: calc(100% - 32px); box-sizing: border-box; padding: 10px 14px; border: 0; border-radius: 8px; background: #efefef; }`,
    `${s("result")} { display: flex; align-items: center; gap: 12px; padding: 8px 24px; }`,
    `${s("inbox")} { display: grid; grid-template-columns: 350px minmax(0, 1fr); height: 100vh; }`,
    `${s("threadList")} { border-right: 1px solid #dbdbdb; overflow: auto; } ${s("threadRow")} { display: flex; gap: 12px; align-items: center; padding: 10px 20px; }`,
    `${s("conversation")} { display: flex; flex-direction: column; min-height: 0; overflow: auto; }`,
    `${s("bubble")} { align-self: flex-start; max-width: 60%; margin: 4px 16px; padding: 8px 12px; border-radius: 18px; background: #efefef; }`,
    `${s("bubbleMine")} { align-self: flex-end; background: #3797f0; color: #fff; }`,
    `${s("card2")} { display: grid; grid-template-columns: 64px 1fr; gap: 10px; align-items: center; margin: 4px 16px; padding: 8px; max-width: 320px; border: 1px solid #dbdbdb; border-radius: 12px; }`,
    `${s("card2")} span { display: block; }`,
    `${s("typing")} { color: #737373; margin: 4px 16px; font-size: 12px; }`,
    `${s("dmComposer")} { position: relative; display: flex; align-items: center; gap: 10px; margin: 16px; padding: 10px 16px; border: 1px solid #dbdbdb; border-radius: 22px; }`,
    `${s("dmComposer")} [contenteditable] { flex: 1; outline: 0; min-height: 20px; }`,
    `${s("dmComposer")} [contenteditable]:empty::before { content: "Message..."; color: #737373; }`,
    `${s("trap")} { position: absolute; left: -10000px; top: auto; width: 1px; height: 1px; overflow: hidden; }`,
    `${s("saved")} { max-width: 935px; margin: 0 auto; padding: 30px 20px 120px; }`,
    `${s("tile")} { display: grid; gap: 6px; }`,
    `${s("upsell")} { width: min(420px, 92vw); background: #fff; border-radius: 16px; padding: 28px; text-align: center; display: grid; gap: 14px; }`,
    `${s("footer")} { color: #737373; font-size: 12px; padding: 24px 0; }`,
  ].join("\n");
}
